### ISSUE TITLE
Chromedp can't restart or clear session after context cancel is called.

### ISSUE THREAD

**Issue by sn0rk64** [chromedp/chromedp#1007]
```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
Google Chrome 97.0.4692.99
$ go version
go version go1.17.6 linux/amd64
```

I was faced with a problem using chromedp and remote headless chrome. I have a code that navigates to some service and does a sign-up process to be possible to upload a file. And it works fine with my local installed google-chrome browser, it does a sign up process, waits until it's done, then does context cancel. When I want to run the process again it successfully repeats the steps: sign up, wait done, context cancel.
But the process fails when I try to run chromedp with remote allocator. For remote chrome I run a docker container
```console
docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell
```
Then I run my code and for the first time it did well, but when I try to run the process again it crashes because it turns out that I'm already authorized in service. So I don't know the reason why the session isn't cleared after the first time? Or maybe the context cancel can't kill the chrome process? I also tried chromedp.Cancel() and there are not errros.

Here is the code of getting context:
```go
func NewCdpContext(ctx context.Context) (context.Context, context.CancelFunc, error) {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", true),
		chromedp.DisableGPU,
		chromedp.Flag("blink-settings", "imagesEnabled=false"),
	)

	ctx, _ = chromedp.NewExecAllocator(ctx, opts...)

	debugUrl, err := getDebugURL()
	if err != nil {
		return nil, nil, fmt.Errorf("get debug url: %v", err)
	}
	ctx, _ = chromedp.NewRemoteAllocator(context.Background(), debugUrl)
	ctx, cancel := chromedp.NewContext(ctx)

	return ctx, cancel, nil
}

func getDebugURL() (string, error) {
	resp, err := http.Get("http://localhost:9222/json/version")
	if err != nil {
		return "", fmt.Errorf("request version: %v", err)
	}

	var result map[string]interface{}

	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", fmt.Errorf("decode json: %v", err)
	}
	return result["webSocketDebuggerUrl"].(string), nil
}
```

**Comment by ZekeLu** [comment]
I guess you mean that the session is cleared when you use `chromedp.NewExecAllocator` (with local installed google-chrome), but it is not cleared when you use `chromedp.NewRemoteAllocator` (with `headless-shell` running in a container).

That's because when you connect to a remote browser with `chromedp.NewRemoteAllocator`, you just create a new tab in the browser. And when the context is cancelled, just the tab is closed (and the session is not cleared in this case).

There are two possible ways to workaround the issue:

1. Build a docker image based on `chromedp/headless-shell` which contains your app. Then run your app in this container. In this case, you can use `chromedp.NewExecAllocator`, and manage the lifetime of the browser.
2. Clear the session yourself. For example, if the session is manged with cookies, you can clear the cookies with [Network.clearBrowserCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-clearBrowserCookies)

**Comment by sn0rk64** [comment]
That was very helpful, thank you

**Comment by yuzhichang** [comment]
@ZekeLu I don't see how to call `Newtork.clearBrowserCookies` from my code. Could you provide an example?

**Comment by ZekeLu** [comment]
@yuzhichang Have you tried this?

```go
	if err := chromedp.Run(ctx,
		network.ClearBrowserCookies(),
	); err != nil {
		log.Fatal(err)
	}
```

**Comment by yuzhichang** [comment]
@ZekeLu It works! However my concern is, `ClearBrowserCookies` may interfere with other running test which use the same chrome-shell container. Clearing cookies of a specific domain sounds better.

**Comment by ZekeLu** [comment]
You can delete specified cookies with [Network.deleteCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-deleteCookies). Before that, you could use [Network.getCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getCookies) list the cookies. You should read https://chromedevtools.github.io/devtools-protocol to understand what are provided by CDP.
