### ISSUE TITLE
Invalid InterceptionId. (-32602)

### ISSUE THREAD

**Issue by nathankodilla** [chromedp/chromedp#1027]
#### What versions are you running?
v0.7.8

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.8
$ google-chrome --version
98.0.4758.102
$ go version
go version go1.17.1 windows/amd64
```

#### What did you do? Include clear steps.

```go
          chromedp.ListenTarget(ctx, func(ev interface{}) {
			go func() {
				switch ev := ev.(type) {
				case *fetch.EventRequestPaused:
					c := chromedp.FromContext(ctx)
					execCtx := cdp.WithExecutor(ctx, c.Target)
					err := fetch.FailRequest(ev.RequestID, network.ErrorReasonFailed).Do(execCtx)
					if err != nil {
						log.Print(err)
					}
				}
			}()
		})

		if err := chromedp.Run(ctx,
			fetch.Enable().WithPatterns([]*fetch.RequestPattern{
				{
					URLPattern: pattern,
					RequestStage: "Request"
				},
			}),
			chromedp.Navigate(url),
		); err != nil {
			log.Fatal(err)
		}
```

#### What did you expect to see?
Requests matching pattern are failed.

#### What did you see instead?
Invalid InterceptionId. (-32602) error. This is occurring randomly and started with no code changes. Same code had been working fine for weeks.

**Comment by ZekeLu** [comment]
This looks like an issue of the website instead of your code. Here is a reported issue that has more information: https://groups.google.com/g/chrome-debugging-protocol/c/Ztez863JGh8?pli=1

You can log the url which causes the error and see what's wrong with that url.

```go
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *fetch.EventRequestPaused:
			// create a new goroutine only when it's necessary
			go func() {
				// use chromedp.Run directly to simplify the source code
				err := chromedp.Run(ctx, fetch.FailRequest(ev.RequestID, network.ErrorReasonFailed))
				if err != nil {
					// log the URL when there is an error
					log.Print(err, ev.Request.URL)
				}
			}()
		}
	})
```

**Comment by nathankodilla** [comment]
@ZekeLu yes it is always the same url since the pattern is a static one. Looking at the linked post it is dealing with the response mime type not matching. In my case I have the fetch on the Request stage and fail it before even going out to the url.

**Comment by ZekeLu** [comment]
I believe that when the error is reported, there is something wrong with the request and it's not sent. Since your purpose is to block the request, you can safely ignore the error.

Here is another case shows when it will result in `Invalid InterceptionId. (-32602)`: https://github.com/chromium/chromium/blob/c4d3c31083a2e1481253ff2d24298a1dfe19c754/third_party/blink/web_tests/http/tests/inspector-protocol/network/response-interception-cancel-xhr-while-responding-error.js . I hope that it helps you understand what does `Invalid InterceptionId. (-32602)` mean.

I can not do anything more without more information. Thanks!

**Comment by nathankodilla** [comment]
@ZekeLu so I can ignore it for when I need to fail; requests. However I am also in need to modify a request response. From the article you linked it happens if a request is cancelled. To the best of my knowledge that is not occurring here. Code for the request modification:

```go
chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *fetch.EventRequestPaused:
			go func() {
				c := chromedp.FromContext(ctx)
				e := cdp.WithExecutor(ctx, c.Target)
				rawJsonB, err := fetch.GetResponseBody(ev.RequestID).Do(e)
				if err != nil {
					log.Println(err) // fails here with the Invalid InterceptionId
				}
				rawJson := string(rawJsonB)
				
                               ...
			}()
		}
	})

if err := chromedp.Run(ctx,
		fetch.Enable().WithPatterns([]*fetch.RequestPattern{
			{
				URLPattern: pattern,
				RequestStage: "Response",
			},
		}),
		chromedp.Navigate(url),
	); err != nil {
		log.Fatal(err)
	}
```

**Comment by ZekeLu** [comment]
The key is to find out why the browser thinks that the interception id is invalid. Like I said before, the current information is not enough to find out the reason. It will be very helpful if you can provide a self-contained minimal reproducer (including the real URL, but a fake HTTP server which can be used to reproduce the issue is better).
