### ISSUE TITLE
Can't run a function of chromedp.ActionFunc inside chromedp.ActionFunc?

### ISSUE THREAD

**Issue by cplasfwst** [chromedp/chromedp#1045]
Can't run a function of chromedp.ActionFunc inside chromedp.ActionFunc?

```
func Fa_First(data sync.Map) chromedp.ActionFunc {
  return func(ctx context.Context) (err error) {
    Here()
  return
  }
}
func Here(data sync.Map) chromedp.ActionFunc {
  return func(ctx context.Context) (err error) {
          fmt.println("It doesn't work here does it?")
  return
  }
}
```

If I want to run something like the Here method inside the Fa_First method, how should I do it? Ask the author for help, thank you very much

**Comment by cplasfwst** [comment]
The above problem, I add .do(ctx) after the method and it seems to work


I take the liberty to ask a question again, I hope the author can answer, I want to ask, why mine, is there any way to judge whether the node or element exists? Returns true if it exists. . . . Not just waiting, I want to be able to judge, how can this be achieved?

**Comment by ZekeLu** [comment]
it's recommended to use `chromedp.Run` to run actions (instead of calling `Do`). See how `chromedp.Run` is implemented:

https://github.com/chromedp/chromedp/blob/b88710e33da89f65c9ed750381125aea3922254c/chromedp.go#L258-L275

>  is there any way to judge whether the node or element exists?

1. `chromedp.Nodes` with the `chromedp.AtLeast(0)` option, and then check the length of the returned nodes.

https://github.com/chromedp/chromedp/blob/b88710e33da89f65c9ed750381125aea3922254c/query_test.go#L1426

2. `chromedp.Evaluate` to run a javascript expression that checks whether the element exists
3. and many more....
