### ISSUE TITLE
Chrome process memory is increasing with long running NewRemoteAllocator with periodic Evaluate (js)

### ISSUE THREAD

**Issue by lundin** [chromedp/chromedp#1046]
Hi,

I have a question for best practice with running a single chrome instance with one tab. First i do chromedp.Run and navigate to a website (that creates a browser/tab). Then i have a message subscriber with nats,.io that can get incoming messages. This subscriber do a chromedp.Evaluate (i think this chromedp.Run is running in the same tab) and send back the output of the js/evaluate. However i can see that the chrome process using top is increasing until it crash. Is this expected that running many console/js in same tab is increasing memory ?

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.8

$ google-chrome --version
Google Chrome 99.0.4844.84 

$ go version
go version go1.17.7 linux/amd64
```

#### What did you do? Include clear steps.

```
//connect to remote instance
devtoolsWsURL := flag.String("devtools-ws-url", "", "devtools url")
        flag.Parse()
        if *devtoolsWsURL == "" {
                log.Fatal("must specify -devtools-ws-url")
        }
        allocatorContext, Alloccancel := chromedp.NewRemoteAllocator(context.Background(), *devtoolsWsURL)
        defer Alloccancel()
   chromedepCtx, cancel := chromedp.NewContext(allocatorContext)
        defer cancel()

//open first tab with run
err = chromedp.Run(chromedepCtx,

chromedp.Navigate("website here"),

chromedp.Evaluate(jsRequest, &res, func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
	return p.WithAwaitPromise(true)
}),
); 

if err != nil {
		panic(err)
	}


//Nats subscriber that runs js commands many times (incoming msg)
nc.Subscribe("time", func(m *nats.Msg) {
  var res interface{}
  err:= chromedp.Run(chromedepCtx,
    chromedp.Evaluate(jsRequest, &res, func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
      return p.WithAwaitPromise(true)
    }),
   ,
  );
  if err != nil {
		panic(err)
	}
 
  log.Printf("chromedp out: %v\n", res)
  
  nc.Publish(m.Reply, []byte(res.(string)) )
  })
```

#### What did you expect to see?
More or less stable memory ?

#### What did you see instead?
Increasing memory

**Comment by ZekeLu** [comment]
Two things to check based on the current information:

1. What is returned as `res`? Maybe you should call `runtime.ReleaseObject` or `runtime.ReleaseObjectGroup` to release the remote object. See

https://github.com/chromedp/chromedp/blob/b88710e33da89f65c9ed750381125aea3922254c/eval.go#L15-L37

2. Try to do the same thing without `chromedp` to figure out whether it's caused by the usage of `chromedp`. You can choose one of (or all of) the following methods to do the same thing:
    - Open the target URL in the browser, and keep running your js code in the console of the DevTools
    - Open the target URL in the browser, and  issue the `Runtime.evaluate` command using [Protocol Monitor](https://chromedevtools.github.io/devtools-protocol/#monitor)
    - Implement the same logic with https://github.com/puppeteer/puppeteer

**Comment by lundin** [comment]
Hello again,
Thanks for your input!
I tried manually with the browser and execute the promise/js code in the console. It did not affect the memory.

But res was made an *runtime.RemoteObject (even though i know it is a string) and i freed it with your suggested	  runtime.ReleaseObject(res.ObjectID) and this actually seems to keep the memory stable after lots of eval execs. So i would say this is the way to go for a long running instance with evals (if that make sense, atleast it seems to work in this case).

**Comment by ZekeLu** [comment]
@lundin Thanks for the feedback!

If you know that it is a string, maybe you should use a `string` instead of `*runtime.RemoteObject`. I think when the type of the variable is a `string`, you don't need to  call `runtime.ReleaseObject`. Would you like to have a test?

Note: when the type of the variable is `string`, make sure the result of the js expression is not `undefined`; otherwise, it will result in an error. See https://github.com/chromedp/chromedp/issues/526
