### ISSUE TITLE
How can I always allow all cookies for a website? 

### ISSUE THREAD

**Issue by cplasfwst** [chromedp/chromedp#1048]
How can I always allow all cookies for a website?
Every time a new page is opened a website (FB) asks if all cookies are allowed. Not friendly to my crawling.
How can I give a website all permissions to cookies?

**Comment by ZekeLu** [comment]
First of all, it's not controlled by any permission.

Cookie consent pop-ups are introduced to comply with the regulations governing cookies under the GDPR and the ePrivacy Directive (see https://gdpr.eu/cookies/). You have to study based on what a concrete website decides not to show the pop-up any more, and then act accordingly.

Most websites use a cookie to indicate that the pup-up has been closed and should not show it any more. In this case, you can specify the user data directory with the `chromedp.UserDataDir` option to persistent the user data (including the cookies) so that the closed pop-up won't be displayed any more. Another choice is to set the cookie on the fly, see an example here:
https://github.com/chromedp/examples/blob/2f7adc7ded326214db81cc6c13d48ecd31af8d31/cookie/main.go#L74-L78

**Comment by cplasfwst** [comment]
Understood, probably understood the meaning, thank you very much for your answer! I thought I needed the browser permission to open it
