### ISSUE TITLE
how to edit document.cookie!

### ISSUE THREAD

**Issue by hzmnet** [chromedp/chromedp#1059]
all version newest

network.SetCookie or running code on UI mode Devconsole are not working! is there any config or how to change it?

**Comment by hzmnet** [comment]
![image](https://user-images.githubusercontent.com/5361750/165670779-3b62be8b-bbe3-440d-bd47-f3b3ca48a82a.png)

**Comment by ZekeLu** [comment]
Please read [this example](https://github.com/chromedp/examples/blob/master/cookie/main.go) carefully. Most of the time, you should pass the actions to `chromedp.Run` instead of calling `action.Do(ctx)` yourself. And I noticed that the URL starts with `file://`. Are you sure that cookie is supported for local file?

If you believe there is something wrong with `chromedp`, please provide a minimal reproducer so that I can look into it.

**Comment by hzmnet** [comment]
hi @ZekeLu  i am not sure CDP support local HTML file with cookies or not. but I still have not found any examples like that!  should I create an HTTP server like your example just for one local HTML?

**Comment by ZekeLu** [comment]
In fact, I don't understand what is your question.

> i am not sure CDP support local HTML file with cookies or not

Let's forget about CDP for now. I want to make sure whether Chrome supports local HTML file  with cookies or not. When I open a local HTML file in Chrome, there is not way to find the cookies. That's why I doubt that it's not supported. Here is the content of the html file, you can have a try yourself.

```html
<html>
    <head>
        <title>test cookie</title>
        <script>
            document.cookie = "key=value";
        </script>
    </head>
    <body>
    </body>
</html>
```

> should I create an HTTP server like your example just for one local HTML?

If you open the HTML file in Chrome directly (`file://` in address bar), then you don't need an HTTP server. If the page is served by an HTTP server, then the URL should be `http...`.

Can you describe what you want to do and what problem you find? And please provide a minimal demo to show that.

**Comment by hzmnet** [comment]
it is not supported!  https://stackoverflow.com/questions/6232331/setting-cookies-using-javascript-in-a-local-html-file
look like only create a HTTP server to solve this problem now!
