### ISSUE TITLE
how to change location and without reload!

### ISSUE THREAD

**Issue by hzmnet** [chromedp/chromedp#1061]
it there any way we could change the document.location to target address which the page is from localhost HTTP server?

such. like

`http://localhost:123/.  =>. https://google.com/`

**Comment by ZekeLu** [comment]
Please elaborate your question.

Here are some references on how to ask a good question:

*  [The XY Problem](https://xyproblem.info/)
*  [Don't ask to ask, just ask](https://dontasktoask.com/)
*  [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
*  [How To Ask Questions The Smart Way](http://catb.org/~esr/faqs/smart-questions.html)

**Comment by hzmnet** [comment]
I copy a website's Html and Js files to local and use golang's s HTTPsetver to serve those templates and statics files as address like "http://localhost:123/",  

problems:
1. the problem is when I use CDP to visit this  `"http://localhost:123/"`, some js codes will call `document.location` to check the website is real, normally if the website is https://google.com/ it will return the same, but in CDP it return `http://localhost:123/`
2. is there any way to change `document.location` value?

**Comment by ZekeLu** [comment]
AFAICT, there is not way to fake `document.location`.

Since the static files are served by you, can you just modify the static file (js code) to disable the checking?

**Comment by hzmnet** [comment]
I see but for some reason, those js files are dynamic updates from the original website  ! so we could edit it!

**Comment by ZekeLu** [comment]
It seems that you can control both the server and the client. In this case, you can make your client resolve the domain to the IP of your own server instead of the original server (for example, adding an entry to the `hosts` file). If you need to connect through HTTPS, you can use a self-signed certificate and tell your client to trust it. And please note that `https://google.com/` is different from `https://google.com:123/`. So your own server should listen on port `443`.

Since there is nothing can be done to `chromedp`. I'm going to closing this issue.
