### ISSUE TITLE
headless-shell: WebGL render performance

### ISSUE THREAD

**Issue by scbizu** [chromedp/chromedp#1146]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.4
$ google-chrome --version
headless-shell(Server) / Google Chrome(Version 104.0.5112.101 (Official Build) (x86_64)) (my local machine)
$ go version
go 1.19 (my local machine ) / go 1.18 (Server)
```

#### What did you do? Include clear steps.

Use headless-shell as the base image (Server) and deploy the same codebase to the server(K8S Cluster , 1C/4G for one pod setup) , the iframe-based render process becomes slow and print the log :

```
[0902/091338.979238:INFO:CONSOLE(0)] "[.WebGL-0x7ac008d9b00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels"
```

But everything works fine and works much more faster on my local machine and do not see such logs.

Did I missed some setups for headless-shell ?

Dockerfile:

```Dockerfile
FROM golang:1.18 AS GOBUILDER

WORKDIR /my/path

COPY bin /my/path/bin
COPY conf/ /my/path/conf

FROM chromedp/headless-shell:latest

WORKDIR /app

ENV shm-size 4G

RUN apt-get update; apt-get upgrade -y ;apt install dumb-init -y
CMD ["dumb-init", "--"]

COPY --from=GOBUILDER /my/path/bin
COPY  --from=GOBUILDER /my/path/conf

ENTRYPOINT [ "/my/path/bin" ]

```

chrome flags:

```Go
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.Flag("disable-web-security", true),
		chromedp.Flag("enable-lazy-frame-loading", false),
		chromedp.Flag("enable-lazy-image-loading", false),
	)
```
#### What did you expect to see?

see the same render speed between server(headless-shell) and my local machine(Google Chrome)

#### What did you see instead?

Server costs almost 5x slower than my local machine.

**Comment by ZekeLu** [comment]
See also #1073.

`headless-shell` could be slow due to:

1. PGO is not enabled. (https://github.com/chromedp/docker-headless-shell/blob/bcd7bbbd76e47e5d216074ce8928d5b6032bab3b/build-headless-shell.sh#L190)
2. WebGL runs on SwiftShader, which runs purely on the CPU.

That said, the comparison does not look reasonable.

1. I assume that `1C/4G` means one CPU core and 4G memory. The configuration is very low comparing to a normal development machine.
2. Since browsing a web page involves loading resources from a website most of the time. The network condition could affect the performance a lot.

**Comment by scbizu** [comment]
Thank you for the advice , could headless-shell give the at least setup in the document ?

**Comment by ZekeLu** [comment]
Do you mean the minimal hardware requirements? Sorry that we don't have a list like that. It really depends on what kind of tasks you want to perform. You have to understand the characteristic of your application and allocate resources accordingly.
If you observe that `headless-shell` performs badly with a moderate configuration, then please provide a self-contained demo so that we can look into it. The demo should contain the html/js used to render the WebGL objects. See a demo here:

https://github.com/chromedp/chromedp/blob/d52f142d01c7ab3391991d23d957e5f9b774ee94/chromedp_test.go#L1055-L1058

**Comment by scbizu** [comment]
Got it , I will try to upgrade the hardware setup and to see if there is some improvements ?

**Comment by scbizu** [comment]
Thank you , after increase the CPU core , things get better now ~
