### ISSUE TITLE
Login session/cookies/user data retention

### ISSUE THREAD

**Issue by hankmoody1** [chromedp/chromedp#1148]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.5
$ google-chrome --version
Version 104.0.5112.101 (Official Build) (x86_64)
$ go version
go version go1.19 darwin/amd64
```

#### What did you do? Include clear steps.

The site Im trying to scrape asks to sign in and then confirm phone number. This happens every time I start scraping.

```go
put your source code here
```

#### What did you expect to see?
I expect it to retain login session/cookies/user data so that I dont need to sign in or verify my phone number again.

#### What did you see instead?
It asks chromedp to sign in again.

 I want to avoid this by retaining whatever session/cookies/user data. Can you please tell me how do I do this? I want to avoid this by retaining whatever session/cookies/user data. Can you please tell me how do I do this?

**Comment by ZekeLu** [comment]
See #818

**Comment by hankmoody1** [comment]
Is chromedp supposed to save cookies/session/user data even after closing the program?

**Comment by ZekeLu** [comment]
As shown in #818, you have to do two things to persistent user data:

1. Use `chromedp.UserDataDir` to specify the directory to store/restore the user data. If you don't do this, `chromedp` will store the data to a temporary directory and remove the directory after the brower exits.
2. Call `chromedp.Cancel` to gracefully close the browser so that the browser has the time to save any unsaved user data.
