### ISSUE TITLE
How to navigate a page using specified profile?

### ISSUE THREAD

**Issue by akhmat** [chromedp/chromedp#1162]
#### What versions are you running?
```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.3
$ google-chrome --version
Version 105.0.5195.127 (Official Build) (64-bit)
$ go version
go version go1.18.2 windows/amd64 
```

#### What did you do? Include clear steps.

```go
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"

	//	"os"
	"strings"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func writeHTML(content string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html")
		io.WriteString(w, strings.TrimSpace(content))
	})
}

func main() {
	//ctx, cancel := chromedp.NewContext(context.Background())
	//defer cancel()
	opts := append(chromedp.DefaultExecAllocatorOptions[3:],
		// if user-data-dir is set, chrome won't load the default profile,
		// even if it's set to the directory where the default profile is stored.
		// set it to empty to prevent chromedp from setting it to a temp directory.
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Flag("profile-directory", "Default"),
		chromedp.UserDataDir(`C:\Users\akh\AppData\Local\Google\Chrome\User Data\`),
		//chromedp.UserDataDir(os.Getenv("CHROME_USER_DIR")),
		// in headless mode, chrome won't load the default profile.
		chromedp.Flag("headless", false),
		chromedp.Flag("disable-extensions", false),
	)
	ctx_, cancel_ := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel_()

	ctx, cancel := chromedp.NewContext(
		ctx_,
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	ts := httptest.NewServer(writeHTML(`<!doctype html>
<html>
<body>
  <div id="content">the content</div>
</body>
</html>`))
	defer ts.Close()

	const expr2 = `(function(d, id, v) {
		var b = d.querySelector('body');
		var el = d.createElement('script');
		el.id = id;
		el.textContent  = v;
		b.insertBefore(el, b.childNodes[0]);
	})(document, %q, %q);`

	var nodes []*cdp.Node
	var outerAfter string
	if err := chromedp.Run(ctx,
		chromedp.Navigate(ts.URL),
		chromedp.Nodes(`document`, &nodes, chromedp.ByJSPath),
		chromedp.WaitVisible(`#content`),
		chromedp.ActionFunc(func(ctx context.Context) error {
			s := fmt.Sprintf(expr2, "thing", "alert('ddd');")
			_, exp, err := runtime.Evaluate(s).Do(ctx)
			if err != nil {
				return err
			}
			if exp != nil {
				return exp
			}
			return nil
		}),
		chromedp.OuterHTML("body", &outerAfter, chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	fmt.Println("Document tree:")
	fmt.Print(nodes[0].Dump("  ", "  ", false))
	fmt.Println("OuterHTML after clicking:")
	fmt.Println(outerAfter)

}

```

#### What did you expect to see?
I want to open a page using a specified profile

#### What did you see instead?
a blank tab opens in chrome with specified profile, and programm exit with error
```
2022/09/16 17:54:18 chrome failed to start:
Opening in existing browser session.
exit status 1```
if you delete these lines, then the page will open correctly in the guest profile
```		chromedp.Flag("profile-directory", "Default"),
		chromedp.UserDataDir(`C:\Users\akh\AppData\Local\Google\Chrome\User Data\`),```

**Comment by ZekeLu** [comment]
Duplicate of #1147.

**Comment by akhmat** [comment]
Thank You.

**Comment by mholt** [comment]
Sorry to comment in a closed and duplicate issue, but I'm new to this and trying to learn. (I'm commenting here because the author of the other issue said, "I do not want to connect to a running browser." -- but that is what I want to do, I think, in my case.)

My goal is to use an existing user session, e.g. my existing Google account, without having to log in again in a separate profile.

My searches have not produced a clear answer, as I've gotten conflicting information on Stack Overflow, GitHub, Chrome docs, issue threads, etc...

- Is it even possible to use chromedp with existing user profiles/sessions? If so, does it require the user to launch Chrome with a special flag (`--remote-debugging-port=...`) to enable remote debugging?

I'm trying to decide which route to take. Launching a new instance of Chrome with a flag is tedious and technical, but having to login again is also tedious.

**Comment by akhmat** [comment]
Chrome must be running in debug mode, otherwise it will not allow interaction with itself.
Accordingly, you need to first run it in debug mode (with flag --remote-debugging-port=9223), then work in it with an existing profile. and then you can connect to this profile via chromedp api.

**Comment by mholt** [comment]
Thanks.

Actually, while trying the "login with the new profile" approach, I found that I couldn't log into Google because the "browser is insecure", so it rejected my login attempt. :(

Some further searching led me to set these options:

```
opts := []chromedp.ExecAllocatorOption{
	chromedp.NoFirstRun,
	chromedp.NoDefaultBrowserCheck,
	chromedp.UserDataDir("/home/matt/.config/google-chrome"),
	chromedp.Flag("enable-automation", true),
	chromedp.Flag("disable-web-security", true),
	chromedp.Flag("allow-running-insecure-content", true),
}
```

and this actually works _as long as Chrome isn't already running_.

If Chrome is running, I get an error:

> [0604/130459.266999:ERROR:chrome_main_delegate.cc(1030)] Web security may only be disabled if '--user-data-dir' is also specified with a non-default value.

But this seems strange since whether Chrome is already running or not should be orthogonal to (have nothing to do with) these flags.

**Comment by akhmat** [comment]
в моем случае не выбирал уже конкретный профиль через апи. а использовал текущий открытый профиль в хроме.
`ctx_, cancel_ := chromedp.NewRemoteAllocator(context.Background(), fmt.Sprintf("ws://127.0.0.1:%d/", port))
	defer cancel_()

	ctx, cancel := chromedp.NewContext(
		ctx_,
	)
	defer cancel()

	//var nodes []*cdp.Node
	var outerAfter string
	if err := chromedp.Run(ctx,
		chromedp.Navigate(ts.URL),
		chromedp.WaitReady(`span[data-testid="test-light"]`),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, exp, err := runtime.Evaluate(js).Do(ctx)
			if err != nil {
				fmt.Printf("ActionFunc err %v\n", err)
				return err
			}
			if exp != nil {
				fmt.Printf("ActionFunc exp %v\n", exp)
				return exp
			}
			return nil
		}),
		chromedp.OuterHTML("body", &outerAfter, chromedp.ByQuery),
		chromedp.WaitReady(`#taskend`),
	); err != nil {
		log.Fatal(err)
	}
`
but a specific profile was also chosen, I remember, but there is no code, you have to try
