### ISSUE TITLE
EventVisibleSecurityStateChanged not emitted in headless mode 

### ISSUE THREAD

**Issue by kshangx** [chromedp/chromedp#1204]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
107.0.5304.87
$ go version
go version go1.18.3 darwin/arm64
```

#### What did you do? Include clear steps.

```go
func main() {
	opts := chromedp.DefaultExecAllocatorOptions[:]
	opts = append(opts,
		// chromedp.Flag("headless", false),
	)

	bctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(bctx)
	defer cancel()

	err := chromedp.Run(ctx, chromedp.Tasks{
		security.Enable(),
		chromedp.ActionFunc(func(ctx context.Context) error {
			chromedp.ListenTarget(ctx, func(ev interface{}) {
				switch v := ev.(type) {
				case *security.EventVisibleSecurityStateChanged:
					fmt.Printf("%+v\n", v)
				}
			})
			return nil
		}),
		chromedp.Navigate("https://example.com"),
		chromedp.Sleep(time.Second * 5),
	})
	if err != nil {
		log.Fatal(err)
	}
}
```

#### What did you expect to see?
EventVisibleSecurityStateChanged should be emitted in headless mode 

#### What did you see instead?
EventVisibleSecurityStateChanged is not emitted in headless mode (tested with default chrome and chromedp/headless-shell image). Event only emitted with headless disabled.

**Comment by ZekeLu** [comment]
I'm not sure whether this event should be emitted or not in headless mode. If you believe it should, please file a bug report to the Chromium team: https://bugs.chromium.org/p/chromium/issues/list.

References:

- the `Security.securityStateChanged` event was added: [Add "Security" domain to devtools protocol.json for the security panel](https://bugs.chromium.org/p/chromium/issues/detail?id=484398)
- the `Security.securityStateChanged` was replaced by the `Security.visibleSecurityStateChanged` event: [DevTools: Modified Security.securityStateChanged to use types and data instead of pre-processed English strings](https://bugs.chromium.org/p/chromium/issues/detail?id=946860)

**Comment by kshangx** [comment]
thanks @ZekeLu 
Reported to Chromium team https://bugs.chromium.org/p/chromium/issues/detail?id=1392805 (this used to work with Security.securityStateChanged)
