### ISSUE TITLE
How to prevent it from autofocus-ing on the address bar?

### ISSUE THREAD

**Issue by jsloring** [chromedp/chromedp#1241]
When the browser is opened

v0.8.7

$ go version
1.17

**Comment by ZekeLu** [comment]
**Anyone who wants to report an issue in the future, please provide a self-contained, executable demo to show the issue. Thank you!**

Here is a demo to show the issue:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Sleep(5*time.Second),
		chromedp.Navigate("https://httpbin.org/anything"),
		chromedp.Sleep(5*time.Second),
	); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by ZekeLu** [comment]
There is an interesting command line option `--app` which will hide the address bar totally:

```go
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("app", "data:,"),
	)
```

**Notes**:

1. New windows opened by this page still get the address bar shown.
2. `data:,` is a data URL, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs.

> Data URLs are composed of four parts: a prefix (`data:`), a [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) indicating the type of data, an optional `base64` token if non-textual, and the data itself:
> ```
> data:[<mediatype>][;base64],<data>
> ```
> The `mediatype` is a [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) string, such as `'image/jpeg'` for a JPEG image file. If omitted, defaults to `text/plain;charset=US-ASCII`

---

Another option is to fork the repository and modify this line:

https://github.com/chromedp/chromedp/blob/bc863fdacf52e8364436fef58455067d74fd9348/allocate.go#L169

Replace `"about:blank"` with `"data:,"`.

It seems that the issue is not a big deal, so I won't apply this change to `chromedp` for now. If you think that this change should be applied to `chromedp`, please vote on this comment with a :+1: reaction. I will apply the change if there are enough votes.
