### ISSUE TITLE
How can I set "disable-web-security" to true with use func "NewRemoteAllocator"?

### ISSUE THREAD

**Issue by weblee8751** [chromedp/chromedp#1262]
Apologize for posting help in issues
I am using func "NewRemoteAllocator" and It has been stable,I hope it will work properly when visiting self-signed websites
I found this [issue](https://github.com/chromedp/chromedp/issues/492)
How can I set "disable-web-security" to true with use func "NewRemoteAllocator"?

**Comment by weblee8751** [comment]
I have tried to use NewExecAllocator, but it has caused serious coredump in the docker. I think NewExecAllocator frequently creates new browsers, while NewRemoteAllocator uses a different tab of one browser. I look forward to your reply

**Comment by ZekeLu** [comment]
I think you meant the chromium command line option `--disable-web-security`. A chromium command line option is applied when a browser instance is started.

> How can I set "disable-web-security" to true with use func "NewRemoteAllocator"?

Since `chromedp.NewRemoteAllocator` is used to connect to an already running browser instance,  there is not chance for the app to set this option. If the pre-started browser instance is started by you, you can pass this option when you start the browser instance. For example, if your remote browser is a container of `chromedp/headless-shell`, you can run it like this:

```sh
$ docker run -d -p 9222:9222 --entrypoint '/headless-shell/headless-shell' chromedp/headless-shell --no-sandbox --use-gl=angle --use-angle=swiftshader --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
```

(The entrypoint parameters are copied from https://github.com/chromedp/docker-headless-shell/blob/master/Dockerfile).

> I think NewExecAllocator frequently creates new browsers, while NewRemoteAllocator uses a different tab of one browser.

See the following example to see how to open multiple tabs in the same browser instance.

https://github.com/chromedp/chromedp/blob/2c1b71999a2f16e3e121672c3a0727cef367ca18/example_test.go#L201-L228

**Comment by weblee8751** [comment]
Thank you very much
Have a goog day
