### ISSUE TITLE
When can chromedp support audio recording?

### ISSUE THREAD

**Issue by sunshinev** [chromedp/chromedp#1285]
#### What did you expect to see?

When can chromedp support audio recording?

#### What did you see instead?

After video recording via chromedp, after synthesizing video via ffmpeg, no sound was found

**Comment by ZekeLu** [comment]
> After video recording via chromedp, after synthesizing video via ffmpeg, no sound was found

If you mean #1283, that's because [Page.screencastFrame](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-screencastFrame) only gives  you image data. And what you have done is converting the images into a video with `ffmpeg`. There is not audio data at all.

As far as I know, CDP does not support audio recording. Please read through the [CDP doc](https://chromedevtools.github.io/devtools-protocol/) to understand what can you do with CDP.
