### ISSUE TITLE
deprecated commands removed?

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#1289]
I was using Network.getAllCookies which is deprecated but still works.

With a recent commit, it was removed:

https://github.com/chromedp/cdproto/commit/6730ecaecb799bdc23b8c9c127d5d245f8f40192#diff-96a7f5c352cd3d2d1ee3c7c55ed95e668c6edb28a4fa337e6c60270471bdab61

**Comment by ZekeLu** [comment]
Yes, https://github.com/chromedp/pdlgen removes deprecated commands unless it's told not to do that (see https://github.com/chromedp/pdlgen/pull/19 for an example).

`Network.getAllCookies` is marked as deprecated in https://github.com/chromium/chromium/commit/f0539553369692ee993a3249ebe9bdb237322abf (Chromium version 111.0.5508.0).

**Comment by kenshaw** [comment]
@tmm1 please note that because of the pace at which the Chromium source tree moves, I made the decision years ago to track the current development branch for APIs (ie, for `cdproto`). 

If you need to revert to an older version of `cdproto`, note that you can use Go modules, and do a `replace()` in your `go.mod` on your project with an older version. Take a look at the [`cdproto` commit history](https://github.com/chromedp/cdproto/commits), find the version you want and the associated commit SHA:

```
commit 078e50cebfff83a65ba784c9edc15a8bec3d462e
Author: Kenneth Shaw <kenshaw@gmail.com>
Date:   Wed Jan 4 08:06:38 2023 +0700

    Updating to 109.0.5414.81_10.9.194.9 definitions
    
```

Then, using the command line, do the following:

```
cd /path/to/project
go mod edit -replace github.com/chromedp/cdproto=github.com/chromedp/cdproto@078e50cebfff83a65ba784c9edc15a8bec3d462e
```
Of course, change the commit SHA (`078e50...`) to the version you need. I would not recommend doing this, however, as the APIs you're relying on are going to be removed shortly (ie, in a few weeks).

If you do do that, you should get a `go.mod` that looks like the following:

```
$ cat go.mod 
module ctest

go 1.20

require github.com/chromedp/chromedp v0.9.1

require (
	github.com/chromedp/cdproto v0.0.0-20230220211738-2b1ec77315c9 // indirect
       # other deps ...
)

replace github.com/chromedp/cdproto => github.com/chromedp/cdproto v0.0.0-20230104010638-078e50cebfff
```

I realize it would be better if the `cdproto` package was tagged, or had tracking branches, but we are dealing with 2 different upstream versions in terms of API (both the "browser" and "v8" definitions), and they can't really be tracked properly using Go's limited `semver` style. Or more or less, I can't think of any way that would be better than doing the above. 

If you had thoughts/ideas on a better version tracking for `cdproto`, I'd be happy to hear your thoughts on the matter.

**Comment by tmm1** [comment]
I had tried to downgrade `cdproto` initially, but since `chromedp` depended on a newer version that didn't work. Using `go mod edit -replace` to pin it to an older version is a good trick- thanks for sharing!

I ended up copying the deprecated definitions I needed into a new package and using them from there, so I can still keep `cdproto` up to date.
