### ISSUE TITLE
Issues with running multiple background jobs concurrently

### ISSUE THREAD

**Issue by profsmallpine** [chromedp/chromedp#1309]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ go version
go version go1.20.4
```

#### What did you do? Include clear steps.

We are doing some larger website scrape jobs using chromedp and headless shell. We are using a dockerfile like so with our go binary:

```
# https://github.com/debuerreotype/docker-debian-artifacts/issues/15
FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM chromedp/headless-shell:114.0.5735.9
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY /worker /
ENTRYPOINT ["/worker"]
```

From here, we are running 

```go
        // Setup chromedp default options
	options := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.UserAgent(userAgent),
		chromedp.DisableGPU,
		chromedp.IgnoreCertErrors,
		// https://stackoverflow.com/questions/69037458/selenium-chromedriver-gives-initializesandbox-called-with-multiple-threads-in
		chromedp.Flag("--disable-software-rasterizer", true),
	)

	actx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(actx)
	defer cancel()

	// Create a timeout as a safety net to prevent any infinite wait loops
	ctx, cancel = context.WithTimeout(ctx, 105*time.Second)
	defer cancel()

	var buf []byte
	var html string

	tasks := chromedp.Tasks{
		network.SetBlockedURLS(blockedURLs),
		chromedp.Navigate(wp.URL),
	}

	tasks = append(
		tasks,
		chromedp.FullScreenshot(&buf, 25),
		chromedp.OuterHTML("html", &html),
	)

	if err := chromedp.Run(ctx, tasks); err != nil {
		return err
	}
```

#### What did you expect to see?

This has been working for awhile but after moving to fargate and attempting to play with some scaling options, we are getting a lot of:

`could not dial "ws://127.0.0.1:38083/devtools/browser/8ba33d85-3367-453c-95f2-91b72ea11b11": read tcp 127.0.0.1:59784->127.0.0.1:38083: read: connection reset by peer`

`chrome failed to start:`
```
chrome failed to start:
[0100/000000.609970:ERROR:[zygote_linux.cc](http://zygote_linux.cc/)(622)] Zygote could not fork: process_type gpu-process numfds 3 child_pid -1
[0100/000000.610099:ERROR:[zygote_linux.cc](http://zygote_linux.cc/)(654)] write: Broken pipe (32)
```

Should we not be running multiple jobs concurrently? Anybody else running into issues with workers?

**Comment by ZekeLu** [comment]
You can run multiple jobs concurrently. But bear in mind that a browser consumes many resources, so you should limit the number of jobs running at the same time. And it's recommended to use a single browser instances to run several jobs (each job running in its own tab). You can create a BrowserContext for each tab with the [chromedp.WithNewBrowserContext](https://pkg.go.dev/github.com/chromedp/chromedp#WithNewBrowserContext) option if you need to isolate the tabs.

**Comment by qu0laz** [comment]
@profsmallpine As ZekeLu said it is resource dependent. I'm not familiar with the error above but have you tried running it outside of docker to see if it makes any difference? Are you running it in docker but are limiting the cpu's available?  Also, are you opening a new tab on every request or are you recycling the tabs?

I went through a similar situation to yours. Initially the chromedp crawler I wrote would open and close tabs with each request and I used a semaphore to limit the number of tabs in addition to a timeout to kill non responsive pages. I saw that there was a lot of CPU cost involved with opening and closing each tab and determined that I needed to recycle the tabs in order to run it successfully concurrently. There was a lot of trial and error involved but I was able to do this by shadowing the context variable through the various functions, while keeping the timeout per page in place and setting a max threshold of 100 pages visited per tab before closing the tab and opening a new one. Reason for the max pages visited per tab is the history of each tab builds up and starts to consume resources, i.e. 30 tabs x 100 history/back items each is manageable, 30 tabs x 10,000 history items each is a bad idea. You could do one browser with 100 or more tabs but I found the sweet spot to be 3-4 browsers with 25 or 33 tabs each.

Also, when I was writing the crawler I was using a newer 12 core ryzen 3900 and was able to do X amount of request per second before I started to see timeouts. When I moved the code to an older dual xeon setup with 24 cores total, I was able to push through an additional 40%+ more request per second. The ryzen has a cpubenchmark of 30,000, the dual xeon with both CPU's combined has a benchmark of 20,000 so in theory the ryzen should be faster. However, after lots of investigation I came to the conclusion that the machine with a worse benchmark performs and more cores performs better because of how go handles threads. If you're making lots of request per second the cpu spends more time switching between threads then actually handling the request itself. Because we're not just making one GET request and getting a single response back, the headless browser is making the initial call and also loading the 10-100+ assets required for that page, spread this out over 100 tabs/pages per second and you will see the problem show up. Typically it would manifest itself in the logs where all of a sudden there would be a giant grouping of timeouts even though the pages are completely valid.

This may not be a direct answer to your problem but hopefully it helps out. If you get stuck I can share with you some code that shows how to handle recycling the tab context + individual tab timeout + max tab limit.

_Note: I haven't worked with chromedp in the last 6 months so i'm not sure if anything has changed in a newer version of chromep and I always ran my code outside of docker._

**Comment by fcuenca4** [comment]
@qu0laz I'm currently trying to achieve something similar, would be great if you can share some of the code! 

Have you tried running your workers on kube? 

Thanks!

**Comment by qu0laz** [comment]
@fcuenca4 I just pulled out the relevant pieces and put them in this [repo here](https://github.com/qu0laz/headless-reuse-browser-sample). This code isn't runnable on its own and is part of a 10kLOC private repo. However I wrote this with about a year of golang experience and it is heavily documented, so it should help quite a bit.

No, I never ran it on k8's. That is because it was bundled with code that would make thousands of get request and dns look ups per second and when I dockerized it overall performance was 30% slower and/or I got more timeouts compared to the binary. Best performance was a binary with an old dual xeon(higher core count) dell workstation from 2015. I'm sure it would work just fine on k8's and if I had the computing resources available I probably would have done the same.

**Comment by profsmallpine** [comment]
@qu0laz Thanks for sharing the details of your approach! We were opening and closing the browser for each request initially. I made it so that we were opening and closing tabs, but that didn't really change the CPU usage. It made it a bit faster overall. We are running on fargate and trying to keep the instance relatively small as our workers also run a bunch of other jobs that need very little CPU, then scaling horizontally when the jobs get backed up. We've found that we can get through ~ 80,000 jobs in ~ 6 hours while only running 2 jobs concurrently on 5 tasks. This is with 2 vcpu in fargate terms. The scraping errors we were running into above was fixed by some trial + error on how to configure chromedp. That now looks like:

```
// Through trial and error we've landed on the following options to pass to chromedp/headless
// chrome. This is a combination of chromedp's DefaultExecAllocatorOptions as well as various
// options mentioned for tooling by the chrome team. See:
// https://pkg.go.dev/github.com/chromedp/chromedp#pkg-variables
// https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md
var chromeOptions = []chromedp.ExecAllocatorOption{
	// NOTE: Currently we're utilizing chromedp's "docker-headless-shell" project which provides a
	//       custom build of the "old" headless chrome. This is fine for now, but that may change
	//       as the chrome team's focus shifts to the new "native" headless mode.
	//       see: https://developer.chrome.com/articles/new-headless/
	chromedp.Headless,

	// Features to enable/disable (https://niek.github.io/chrome-features/)
	chromedp.Flag("enable-features", "NetworkService,NetworkServiceInProcess2"),
	// TODO: remove AvoidUnnecessaryBeforeUnloadCheckSync below
	// once crbug.com/1324138 is fixed and released.
	// AcceptCHFrame disabled because of crbug.com/1348106.
	chromedp.Flag("disable-features", "site-per-process,Translate,BlinkGenPropertyTrees,InterestFeedContentSuggestions,CalculateNativeWinOcclusion,DialMediaRouteProvider,OptimizationHints,MediaRouter,BackForwardCache,AcceptCHFrame,AvoidUnnecessaryBeforeUnloadCheckSync"),

	// Other flags from chromedp.DefaultExecAllocatorOptions
	// see: https://pkg.go.dev/github.com/chromedp/chromedp#pkg-variables
	chromedp.NoFirstRun,
	chromedp.NoDefaultBrowserCheck,
	chromedp.Flag("disable-background-networking", true),
	chromedp.Flag("disable-background-timer-throttling", true),
	chromedp.Flag("disable-backgrounding-occluded-windows", true),
	chromedp.Flag("disable-breakpad", true),
	chromedp.Flag("disable-client-side-phishing-detection", true),
	chromedp.Flag("disable-default-apps", true),
	chromedp.Flag("disable-dev-shm-usage", true),
	chromedp.Flag("disable-extensions", true),
	chromedp.Flag("disable-hang-monitor", true),
	chromedp.Flag("disable-ipc-flooding-protection", true),
	chromedp.Flag("disable-popup-blocking", true),
	chromedp.Flag("disable-prompt-on-repost", true),
	chromedp.Flag("disable-renderer-backgrounding", true),
	chromedp.Flag("disable-sync", true),
	chromedp.Flag("force-color-profile", "srgb"),
	chromedp.Flag("metrics-recording-only", true),
	chromedp.Flag("safebrowsing-disable-auto-update", true),
	chromedp.Flag("enable-automation", true),
	chromedp.Flag("password-store", "basic"),
	chromedp.Flag("use-mock-keychain", true),

	// Other flags mentioned for tooling
	// see: https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md
	chromedp.Flag("disable-component-extensions-with-background-pages", true),
	chromedp.Flag("autoplay-policy", "user-gesture-required"),
	chromedp.Flag("deny-permission-prompts", true),
	chromedp.Flag("disable-notifications", true),
	chromedp.Flag("block-new-web-contents", true),
	chromedp.Flag("noerrdialogs", true),
	chromedp.Flag("disable-component-update", true),
	chromedp.Flag("disable-domain-reliability", true),
	chromedp.Flag("no-default-browser-check", true),
	chromedp.Flag("no-pings", true),
	chromedp.Flag("no-service-autorun", true),
	chromedp.Flag("disable-crash-reporter", true),
	// https://github.com/GoogleChrome/chrome-launcher/blob/f1baa9af20db9c1e3c55187ba9e91c6f1cee99e9/src/flags.ts#LL60
	chromedp.Flag("force-fieldtrials", "*BackgroundTracing/default/"),

	// Flags that we believe help us avoid various issues
	chromedp.IgnoreCertErrors,
	// All current literature states that "DisableGPU" is no longer needed, but it seems to solve
	// some problems (and our workers don't have a GPU anyway).
	// e.g. https://github.com/chromedp/chromedp/issues/904
	chromedp.DisableGPU,
	// https://stackoverflow.com/questions/69037458/selenium-chromedriver-gives-initializesandbox-called-with-multiple-threads-in
	chromedp.Flag("disable-software-rasterizer", true),

	// Override the default user agent
	chromedp.UserAgent(userAgent),
}
```

I hadn't thought about reusing tabs and will try that approach next. Thanks again for the writeup of your experiences 🤗
