### ISSUE TITLE
Possible Memory Leak Issue Using Pool

### ISSUE THREAD

**Issue by carusyte** [chromedp/chromedp#134]
My program crawls the web using chromedp.Pool for quite some time and the memory usage grows horribly and won't subside. My instincts is that the many channels used in the TargetHandler are used without calling close() anywhere. Is any body else experiencing the same issue? Will get to dig deeper whenever I've got the time.

**Comment by carusyte** [comment]
Sorry, it seems there is no need to close a channel after use as documented by the official. See: [Is It OK to leave a channel open?](https://stackoverflow.com/questions/8593645/is-it-ok-to-leave-a-channel-open)

I got it fixed by modifying `*Pool.Shutdown()` to call `r.Release()` instead of `r.cancel()` which is just canceling the context only, and by modifying `*Res.Release()` to call `r.CDP().Shutdown(r.ctxt)` to actually close the target. My code: [pool.go](https://github.com/carusyte/chromedp/blob/master/pool.go)

**Comment by rjeczalik** [comment]
@carusyte Would it be possible for you to send PR with your changes? I've observed possibly the same issue, but did not get around to troubleshooting it.

**Comment by carusyte** [comment]
@rjeczalik I submitted a PR but the CI complaints about something,

```
*** Test killed with quit: ran too long (10m0s).
exit status 2
FAIL	github.com/knq/chromedp	600.010s
The command "CHROMEDP_NO_SANDBOX=true go test -v -coverprofile=coverage.out" exited with 1.
```

Not sure if it is critical, and what caused the test running too long...

**Comment by maxence-charriere** [comment]
I noticed the same, my service memory was going up when using it and had to revert.

![screen shot 2018-05-31 at 10 47 58 am](https://user-images.githubusercontent.com/2692731/40798579-3baad44a-64c0-11e8-87bb-93670781ed9d.png)

**Comment by mvdan** [comment]
We've fixed a couple of goroutine leaks in the master branch; please try the latest tagged v0 version.

We're currently designing the new v2 version, which will have a different internal design. Since this issue is quite old and it seems like the goroutine leak was never pinned down, I'm going to close this issue for now.

Once v2 is ready, if you still find any goroutine leaks, we'll be happy to accept PRs. If you'd like to work on a PR against the current master you're welcome to, but it's unlikely we'll tag another v0 release. In any case, CI should be much faster and more stable now.
