### ISSUE TITLE
How to turn off the notification that the browser is being tested

### ISSUE THREAD

**Issue by CreamCati** [chromedp/chromedp#1392]
chromedp.Flag("disable-infobars", true),

this code has no effect

**Comment by ZekeLu** [comment]
I guess you mean this:

![image](https://github.com/chromedp/chromedp/assets/1063615/0e08ed83-34d4-4ed0-9eb2-8c585fb51500)

Here is the status quo from [the comment 20 of "Issue 826578: Remove --disable-infobars"](https://bugs.chromium.org/p/chromium/issues/detail?id=826578#c20):

> Flag --disable-infobars has been removed due to abuse reports: https://bugs.chromium.org/p/chromium/issues/detail?id=1095215#c8
>
> The infobars can be disabled via enterprise policies (https://bugs.chromium.org/p/chromium/issues/detail?id=1095215#c8):
>    - Windows - works only for domain-joined computers
>    - Linux - any computers: https://bugs.chromium.org/p/chromium/issues/detail?id=818483#c41, https://bugs.chromium.org/p/chromium/issues/detail?id=818483#c43
>
> The users of not domain-joined Windows computers are still not satisfied with the solution: https://bugs.chromium.org/p/chromium/issues/detail?id=1095215
>
> Idea: Shall we reintroduce --disable-infobars in CfT?
>
> Pros:
> - Regular users are not supposed to use this channel and therefore they will not be subject to the attacks involving --disable-infobars
> - The users of Stable and Beta channel will be able to return to the status quo before the --disable-infobars prohibition
>
> Cons:
> - Canary and Dev channel users on not domain-joined Windows computers still cannot disable infobars. They might opt out from using the earliest previews. This is not good as these people might contribute so valuable early feedback on other issues.
> - The whole solution becomes more and more fragmented.

Interestingly, removing the `enable-automation` switch will hide this inforbar (tested in `Chrome 118.0.5993.117`):

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Sleep(10*time.Second),
	); err != nil {
		log.Fatal(err)
	}
}
```

I'm afraid that the behavior of the `enable-automation` switch will be changed due to the same reason as why `--disable-infobars` was removed.

See also:

- https://github.com/chromedp/chromedp/issues/557#issuecomment-843893358.
- https://github.com/chromium/chromium/commit/7a66b24c10161a5db8668729a97ac95cee9068e2
- https://github.com/chromium/chromium/commit/54c54afcd1d3b790a15de0fc70caeff5350da5bb
