### ISSUE TITLE
not happy about it

### ISSUE THREAD

**Issue by stephencheng** [chromedp/chromedp#165]
hi @kenshaw I'd like to express that I am not happy about the fix for the issue reported here:
https://github.com/chromedp/chromedp/issues/75

This issue was reported in june last year, it was followed by a few other people and provided a fix, and there is another merge request page for this. I also provided a testing report base on my particular case about it and showing it has positive results.

You mentioned this might need more tests and you will merge it back, however this has never happened.

In Dec:
1. you split the codebase to a few individual ones
2. you closed the merge request (the issue page is still open though)
3. you did not answer when this will be merged back
4. you did not announce the plan what to do

I(or other users of the project) could take my patience on the fact that you are busy and let's leave it there for sometime and wait for later and we will probably just use the hack for the time being. However this whole thing is just so not pleasant because:

1. user has to fork and maintain their own code base and use special way to "overwrite" to hack the go library management. This has to be applied every time if the repo is updated in anyway.
2. now due to the split of the codebase, this is all broken. The splitting leaves a gap for the other people's patch to be patched again and personally I spent a night and just couldn't easily figure it out what to manually patch by hands due to massive changes. 

What I am not happy are:
1. The process is not agile. Users are expecting adopting fixes/features quicker. Yes, I understand you have limited time for testing and coding etc. Then this comes to second problem:
2. Can you grant more people the permission and let them contribute to the project? As I can see there are quite a few guys helped patching, testing etc. Can you let them merge the code and responsible for the change they made? or at least allow the trial patch to be in a branch to be verified, so the changes could be carried over to new split code repos.
3. No communication the plan of changes, like the codebase split
4. I don't understand why no action on this serious performance issue or plan towards it. I message in the closed merge request and the issue, there seems no reply and no explanation and no plan. 

I could appreciate the work you have done and understand time is limited for everybody. And you might not have time to focus on something interest the user but not some more important things to you and your team.

Once again, I wish https://github.com/chromedp/chromedp/issues/75 could be looked at and I am hoping there could be a way for more users to participate in the project and contribute and eventually benefit all.

Excuse and ignore my rumbly noise and focus the issue. 

Thanks

**Comment by kenshaw** [comment]
Hi Stephen,

I understand your concerns. Please note that everything is MIT licensed; if you are unhappy with the pace of development on this project, feel free to fork / create a new project. I would also like to stress that it is rather easy -- using git -- to merge changes from others into your own source tree and bypass this project completely. 

A large revision of `chromedp` is coming, but it can't be pushed "incrementally" as it has significant architecture revisions / changes to it. I really do appreciate the contributions you and others have made to the project, but its worth mentioning that a number of the submissions do not "fix" the issues they claim to to or are otherwise subpar -- missing relevant documentation such as inline comments, are non-idiomatic Go, etc -- and may not be merged by me for reasons that may I am not necessarily able to share publicly, such as they break code in non-public repositories.

Additionally, it should be mentioned that GitHub issues really shouldn't be used for the airing of grievances. I'm more than happy to address your concerns with more details privately. Feel free to email me directly at kenneth.shaw@knq.io if somehow `chromedp` is unsatisfactory for you. 

Please note that I read/review every issue and PR that comes across my table via GitHub, however I may not have time to respond to each, nor do I necessarily feel that anything I have to say would be relevant or add to the existing discussion.

**Comment by stephencheng** [comment]
@kenshaw 

Apologies for grievances here. 

You mentioned large revision coming soon. Does it include the patch of this or the problem could possibly going away due to architecture changes? 

The patch is important to me, if I see there wouldn't be possible available in short time, I'd make bitter choice to just use the older version before the split and put the patch on top it for another few months and see how new code base doing.

Btw, is it possible you could put a guide somewhere for contributors to follow, like your standard, preferences, rules etc so that better quality of merge request could be. I understand you want the best of best from the code/patch and I respect that entirely.

**Comment by kenshaw** [comment]
I don't have a specific ETA at the moment. The recent breaking up of the project into multiple repositories is about 20% of the effort so far on the revision. The revised "architecture" of `chromedp` was completed around the same time as when I broke the projects up (ie, 2 weeks ago or so). However, those changes aren't ready yet for the public. Additionally, I want to make sure that I'm avoiding all of the locking/etc. issues that were reported; there has been considerable effort made on this front, to ensure that the "new" model moving forward will be adaptable and usable. My plans also are to "lock" the API down, and start publishing the main package using dependency locks (via `dep`).

**Comment by stephencheng** [comment]
@kenshaw trying to reach with your mail but seems the domain name is not resolvable anymore.

I wonder how is going on with the "new" model?

Thanks
