### ISSUE TITLE
Autocreate DefaultUserDataTmpDir folder

### ISSUE THREAD

**Issue by rubenwap** [chromedp/chromedp#169]
The `DefaultUserDataTmpDir` in Windows is `c:\temp` 

If this folder doesn't exist, an error is thrown. 

Would it be possible to autocreate it instead?

**Comment by kenshaw** [comment]
Yes, but this behavior will not be changed on Windows. The issue is that multiple versions of Windows have different (non-static) default paths that may or may not exist. It is out-of-scope of the responsibility of `chromedp` to detect which version of Windows is being run, and to create the directory, not to mention that likely in a multi-user environment the running Go code likely does not have permissions to create a folder in that path.

It is fairly easy / straight-forward to write launching code in Go that checks for the presence of a directory, and if it doesn't exist, creates it:

```go
fi, err := os.Stat(`c:\temp`)
switch {
case os.IsNotExist(err):
  err = os.MkdirAll(`c:\temp`)
  if err != nil { return err }
case err != nil:
  return err
case !fi.IsDir():
  return errors.New(`c:\temp is not a directory`)
}
```

(please note I wrote the above from memory, and I have not tested if it actually works)

**Comment by rubenwap** [comment]
Thanks for checking this. Actually you are right, it´s a better idea to create the folder from my own script rather than expect it from `chromedp`. 

Thanks again for the great work you are doing.
