### ISSUE TITLE
Open Chrome in foreground

### ISSUE THREAD

**Issue by mightyguava** [chromedp/chromedp#171]
Is there a way to have chromedp open Chrome in the foreground, or within an existing normal (non-debugging) browser window as a new tab? A way to bring the window to foreground would be good too.

I know it's kind of weird to want this for driving web testing, but I'm looking to use chromedp as something to do something similar to `livereload`, for iterative local web development.

Thanks!

**Comment by RidgeA** [comment]
Did you try to run chrome without `--headless` flag ?

**Comment by mightyguava** [comment]
Yeah, I'm not running it with the headless flag. The Chrome instance is open, and I can switch to it. I'd just like it to be open to my existing browser.

I'm on OSX. Running with a blank `user-data` flag does open chrome in my existing browser, but then chromedp can't seem to connect to it.

**Comment by kenshaw** [comment]
If you use `chromedp/runner` without passing the headless flags, Chrome will be launched / run by default. This is how I build scripts using `chromedp` personally, and this is the default behavior of the package. If you'd like Chrome to stay open (so that you can manually open devtools or some such), then you can simply remove the calls to `Shutdown`, or otherwise cause the Go code to wait indefinitely.
