### ISSUE TITLE
Retrieving full response and headers

### ISSUE THREAD

**Issue by theduke** [chromedp/chromedp#182]
In puppeteer, accessing the primary response of a page load is easy.

```javascript
const response = await page.goto('http://google.com');
```
I need to get the response headers, status code and full response body of a request.

Is there a way to do this in chromedp?

See https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md.

**Comment by jredl-va** [comment]
@kenshaw My apologies for the interruption. I was just about to launch into a way of performing the above and prior to starting I figured I should stop and ask the expert. 

Do you have any recommendations on where to add an interceptor to extend the chromdp api for access to response headers, status code and full response body?

Is the approach here: https://github.com/chromedp/chromedp/pull/132/files perhaps a good place to start?

**Comment by kenshaw** [comment]
@jredl-va I've been working on a replacement for the existing `Handler` for `chromedp` -- but it is not done yet, and may not be done for a while due to time constraints. The issue is that there needs to be two "handlers" in `chromedp`, one monitoring/managing the network events, and the other managing the page + dom events. The current `chromedp` architecture doesn't pay attention to any of the network events, which is, as far as I am aware, the only way to capture the actual request/response information, and do the equivalent of "view source" or do a "HAR recording".

**Comment by jredl-va** [comment]
@kenshaw that's great to here and thanks for the reply. Do you have a work in progress by  any chance? I ask as this is a very promising project and we would love to be able to contribute to it.

**Comment by dmitry-vovk** [comment]
I solved the issue this way: https://gist.github.com/dmitry-vovk/737385788cb6f287dfb657723f94cb59

**Comment by dmitry-vovk** [comment]
Logging net events into a log file does not work in headless mode. So I created a PR https://github.com/chromedp/chromedp/pull/231 that allows streaming network events for capturing.

**Comment by mvdan** [comment]
This works in master; see https://github.com/chromedp/chromedp/issues/105.
