### ISSUE TITLE
"timeout waiting for initial target"

### ISSUE THREAD

**Issue by daltonfury42** [chromedp/chromedp#202]
I get this error when I do a pool.Allocate():

`timeout waiting for initial target`

> 	dataDirPath := "userDirs/" + strings.Replace(machine.IP, ".", "_", -1) + "/" + machine.Port
	// create chrome instance
	opts := []runner.CommandLineOption{
		runner.HeadlessPathPort("/usr/bin/chromium", 9000+id),
		runner.Flag("disable-gpu", true),
		runner.Flag("no-first-run", true),
		runner.Flag("no-default-browser-check", true),
		runner.Flag("no-sandbox", true),
		runner.Proxy("socks5://" + machine.IP + ":" + machine.Port),
		runner.UserAgent(machine.UserAgent),
		runner.UserDataDir(dataDirPath),
	}

>	mutex.Lock()
	pool := bc.pool
	ctxt := bc.ctxt
	mutex.Unlock()

>      c, err := pool.Allocate(ctxt, opts...)
>	if err != nil {
		return nil, err
	}

Here bc is a global struct with the pool handle.

What could be wrong?

Chromium version: Chromium 67.0.3396.79 Arch Linux

**Comment by mvdan** [comment]
This tends to be because there's an issue running Chrome. Arguably chromedp could give a better error message, but Chrome also makes that kind of difficult.

I'd suggest running the chrome command that chromedp executes, and seeing what its result is. It's probably erroring almost immediately, which is something I too encountered recently.

**Comment by mvdan** [comment]
Also see https://github.com/chromedp/chromedp/issues/153.

**Comment by mvdan** [comment]
I got no response, so I assume this is no longer a problem. If it is, feel free to reopen or open a new issue.
