### ISSUE TITLE
i need a working example of chromedp using kb.paste in headless or in ducker

### ISSUE THREAD

**Issue by AmrAlfoly** [chromedp/chromedp#214]
i use this beautiful package in my tests and it's working well in normal mode but i needed to make it work in headless or in Ducker  
i tried it but there is a crucial thing in my tests not working in headless when i try to paste data from clipboard to the textarea  i use the kb.paste and it's not working on headless or in ducker
can anyone provide me with a simple working example of chromedp using kb.paste in headless

**Comment by kenshaw** [comment]
I don't think using the `kb.Paste` would work ever, in headless. Can it work in other packages (puppeteer, selenium, etc)? If so, if you can provide a recording of it it puppeteer/selenium/something else working in headless, I can likely fix whatever the issue(s) is(are). Understand that in Windowing systems (ie, Win32, Cocoa, XWindows, etc.), the Windowing system itself manages the copy/paste buffer from the "operating system" side. Since `headless_shell` and/or Chrome invoked with `--headless` has no windowing/rendering UI, I would assume that copying/pasting would not be possible, as there is no Win32/Cocoa/XWindows copy/paste buffer that's available. I can't say that for sure is the issue, but this is my expectation of what the root cause of the issue would be.

**Comment by AmrAlfoly** [comment]
is there any alternative way to sendkeys ?
because the text is very large 
i tried setvalue but it crashes on big text

**Comment by kenshaw** [comment]
@AmrAlfoly can you expand on what is crashing? Chrome or `chromedp`? If you can record a session using Selenium or some other automation system, where the system copy/paste buffer is inserted into a field using keyboard's paste key, I'd gladly fix this (assuming it's even possible).

My other suggestion would be to use a JavaScript (ie, `chromedp.Evaluate`) to inject the value, if `chromedp.SendKeys` isn't working.
