### ISSUE TITLE
Unable to use the runner package

### ISSUE THREAD

**Issue by CorentinB** [chromedp/chromedp#318]
Hi!
I'm trying to use the `runner` package to specify headless command line option and user data directory, I'm trying to do that based on other examples I saw in the issues / stackoverflow, but I'm unable to import / use `github.com/chromedp/chromedp/runner` it looks like it doesn't exist anymore.

It also look like I'm missing something obvious here, I'm going crazy..

Thanks for any help!

**Comment by pmurley** [comment]
Yup, I believe  this is because after the refactor that was done (is still being done), there is no `runner` anymore - browsers are just launched as shown below.

Here's an example that I think will launch a browser in headless mode, although I haven't run it:

```golang
func example () {
    var opts []chromedp.ExecAllocatorOption{chromedp.Flag("headless", true)}

    allocContext, _ := chromedp.NewExecAllocator(context.Background(), opts...)
    ctx, cancel := chromedp.NewContext(allocContext)
    defer cancel()

    err = chromedp.Run(cxt, Navigate("www.google.com"))
    if err != nil {
        fmt.Println(err.Error())
    }
    time.Sleep(5 * time.Second)

} // Browser closes here
```

You should also be able to use the built-in function [here](https://godoc.org/github.com/knq/chromedp#Headless). Hope that helps!

**Comment by CorentinB** [comment]
@pmurley  Thanks a lot for your help!
I did not know that a refactor was being done, that makes sense now.

Keep up the good work!
