### ISSUE TITLE
a very simple question

### ISSUE THREAD

**Issue by jerry94test** [chromedp/chromedp#344]
```go
package main

import (
"context"
"fmt"
"github.com/chromedp/chromedp"
)

func main() {
	c, can := chromedp.NewContext(context.Background())

	run := chromedp.Run(c, chromedp.Navigate("https://www.google.com"))
	fmt.Println(run)
	defer  can()
}
```
I Use  JetBrains ide.golang debug mode result is
Context canceled

if is no debug result is nil

**Comment by jerry94test** [comment]
go version go1.12.5 windows/amd64
chromedp v.0.3

**Comment by tmm1** [comment]
You need to call `c.Wait()`

**Comment by mvdan** [comment]
I'm not sure how I can help you here. I don't use JetBrains, and like you say, this works on a regular console.

My best guess would be that the shell within JetBrains doesn't allow you to start Chrome. Perhaps try starting it directly and see what happens. Otherwise, enable debugging or add prints to investigate. I don't use said IDE, so there's not much I can do here.

**Comment by jerry94test** [comment]
github.com/go-delve/delve 
The same is true with vscode, as long as debug mode is used.
Can you tell me which editor you are using?
