### ISSUE TITLE
How to store chromedp.network.Headers into golang.http.Header?

### ISSUE THREAD

**Issue by LeMoussel** [chromedp/chromedp#399]
Chromedp use type  `network.Headers`  like this 
`type Headers map[string]interface{}` (https://godoc.org/github.com/chromedp/cdproto/network#Headers)
I would like to store the `network.Headers` values into `http.Header`.  
`type Header map[string][]string ` (https://godoc.org/net/http#Header) 

Would you have a solution to do that?

**Comment by mvdan** [comment]
Upstream's documentation just says that the headers type is just an "object", hence why the Go type is a bit unhelpful. See https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Headers.

Have you inspected the values? I'm sure that the entry values end up being something like `string` or `[]string`.

**Comment by kenshaw** [comment]
Note that the [`chromedp` examples](https://github.com/chromedp/examples/blob/master/headers/main.go) has a `headers` example that shows how to _send_ headers, which can be done simply as:

```go
network.SetExtraHTTPHeaders(network.Headers(map[string]interface{}{
    "X-My-Header": "my value",
})
```

Previously, to _intercept_ the headers from a site you would have used the various `Network.*` events and the `Network.Headers` type. This essentially a `map[string]string`, however the return type as `object` is correctly represented on the wire as `map[string]interface{}` in Go. You can iterate the map elements, and save them into a `http.Header` type like the following:

```go
headers := <<< get headers >>>
res := make(http.Header)
for k, v := range headers {
    res.Add(k, v.(string))
}
```

While it is still possible to use Chrome's `Network` domain for intercepting events, this mechanism has been deprecated and Chrome has instead introduced the more robust `Fetch` domain (ie, [`cdproto/fetch`](https://godoc.org/github.com/chromedp/cdproto/fetch)). This should be used instead of `cdproto/network.*` for any new development.

In the `cdproto/fetch` package, there is a [`HeaderEntry`](https://godoc.org/github.com/chromedp/cdproto/fetch#HeaderEntry) type that has a `Name` and `Value` member, which is much clearer than the former JSON object result. The `cdproto/fetch.HeaderEntry` type is used in the various fetch domain events and commands. To convert a `fetch.HeaderEntry` to a `http.Header` you would do something like the following:

```go
headers := <<< get headers >>>
res := make(http.Header)
for _, h := range headers {
    res.Add(h.Name, h.Value)
}
```

To convert from `http.Header` to `fetch.HeaderEntry`:

```go
headers := <<< get headers >>>
var res []*fetch.HeaderEntry
for k := range headers {
    res = append(res, &fetch.HeaderEntry{Name: k, Value: headers.Get(k)})
}
```
