### ISSUE TITLE
chromedp.Value: "unexpected end of JSON input"

### ISSUE THREAD

**Issue by adiabatic** [chromedp/chromedp#410]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.3.1
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 75.0.3770.100 
$ go version
go version go1.12.6 darwin/amd64
</pre>

#### What did you do? Include clear steps.

I ran this test program:

```go
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"

	"github.com/chromedp/chromedp"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", writesHTML(slash))

	server := httptest.NewServer(mux)

	cdpContext, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var viaEvaluate string
	var viaValue string

	if err := chromedp.Run(cdpContext,
		chromedp.Navigate(server.URL),

		chromedp.Evaluate(`const e = document.querySelector('h1'); if (e) e.innerText; else '';`, &viaEvaluate),
		chromedp.Value("//h1", &viaValue),
	); err != nil {
		log.Fatal(err)
	}

	if viaEvaluate != viaValue {
		fmt.Printf("Expected .Evaluate and .Value to give the same results. Got:\nviaEvaluate:\t%s\nviaValue:\t%s\n", viaEvaluate, viaValue)
	} else {
		fmt.Println("got:", viaEvaluate)
	}
}

func writesHTML(h string) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		io.Copy(w, strings.NewReader(h))
	}
}

const slash = `<!DOCTYPE html>
<html lang='en-US'>
<head>
	<meta charset='UTF-8'>
	<title>Test Page</title>
</head>
<body>
    <h1>Test Page</h1>
</body>
</html>
`
```

#### What did you expect to see?

I expected to see `got: Test Page`.

#### What did you see instead?

```
2019/06/29 19:34:34 unexpected end of JSON input
exit status 1
```

If I comment out the `chromedp.Value` line, I merely get the expected output that says that "Test Page" doesn't match "".

This is a chromedp 0.3.1-based test case of something I saw in a chromedp 0.2.0-based project. In the older-chromedp project, a similar .Value call appears to not fill the `value *string` parameter.

Any idea of what might be happening?

**Comment by mvdan** [comment]
This is a confusing error - we should definitely fix that one way or another.

What are you trying to do? `chromedp.Value` obtains a node's value, which is useful for nodes like an input form field. You simply have an `h1` node, so you probably want `chromedp.Text`, which obtains the `textContent` field. In your example, that seems to be exactly the same as `innerText`.

I think that in your code above, `chromedp.Value` should either give a useful error, or provide an empty string.

**Comment by adiabatic** [comment]
> What are you trying to do? chromedp.Value obtains a node's value, which is useful for nodes like an input form field. You simply have an h1 node, so you probably want chromedp.Text, which obtains the textContent field. In your example, that seems to be exactly the same as innerText.

Oh, huh. I had no idea. Could "Only input forms and textareas have values. To get the text content of a node, use chromedp.Text." or similar be added to the godoc comment for `Value`?

**Comment by kenshaw** [comment]
The `chromedp.Value` action is meant to be used to get the value of, eg, a form or input element, and is simply a wrapper around the `chromedp.JavascriptAttribute` action. 

As @mvdan mentioned, if you wanted the _text content_ of the matching selector, then use the `chromedp.Text` action. If you need to retrieve the _attribute value_ of the HTML element that the selector matches, then use `chromedp.AttributeValue` and/or use `chromedp.Attributes` if you'd like to retrieve all attributes for the selector in a single pass.

The reason the error is confusing, is because `chromedp.Value` is ultimately a wrapper around `chromedp.Evaluate`, which is calling (essentially) the following on the browser: `$x('//h1')[0].value`, which will fail if the value is undefined.

If you try `$x('//h1')[0].value` in Chrome's DevTools, on a page with a H1 element, you will see that there is no `value` field on the element, which is a [`HTMLElement` field](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement).

We can likely make the error returned by the `chromedp.Evaluate*` actions slightly better, and I might make a point of doing so for the upcoming release.

**Comment by mvdan** [comment]
I think the fix could be simpler. In the various functions that do JSON decoding of JS values/objects, we should return a simple error before doing the JSON decoding if the JS value/object is null or empty. At least in this case, I think that would have told the user "this node has no value", which might steer them in the right direction.

**Comment by mvdan** [comment]
> or similar be added to the godoc comment for Value?

For what it's worth, this was done.

I'm now looking at returning a slightly better error in this case.
