### ISSUE TITLE
FullXPath isn't working correctly

### ISSUE THREAD

**Issue by ZzEeKkAa** [chromedp/chromedp#412]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.0.0-20190617065505-d55cf9043e05
$ google-chrome --version
Version 75.0.3770.100 (Official Build) (64-bit)
$ go version
go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.
Here is an example of page, with dynamic DOM tree, that provides bad xpath:
https://github.com/ZzEeKkAa/chromedp-xpath
Some snippets:
main.go
 ```go
ctx, cancel := chromedp.NewContext(context.Background())
defer cancel()

absPath, err := filepath.Abs("template.html")
if err != nil {
	panic(err)
}
if err := chromedp.Run(ctx, chromedp.Tasks{
	chromedp.Navigate("file://" + absPath),
	chromedp.Query("a.toggle-nav", chromedp.ByQuery),
	chromedp.QueryAfter("a[href='#mm-2']", func(ctx context.Context, nodes ...*cdp.Node) error {
		fullPath := nodes[0].FullXPath()
		fmt.Println("[[FullXPath]]", fullPath)
		if fullPath != "/html[1]/body[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]" {
			return errors.New("wrong path")
		}
		return nil
	}, chromedp.ByQuery),
}); err != nil {
	log.Fatal(err)
}
```

template.html
```html
<!DOCTYPE html>
<html>
<body>
    <div>
        <a href="#my-menu" class="toggle-nav">Nav</a>
        <div id='my-menu'>
            <ul class="sf-menu">
                <li>
                    <a href="#">Item</a>
                    <ul></ul>
                </li>
            </ul>
        </div>
    </div>
</body>
<script>
    var scr = {
        "scripts": [
            {"src": "./libs.min.js", "async": false},
            {"src": "./script.js", "async": false}
        ]
    };
    !function () {
        "use strict";
        window.onload = function () {
            if ("[object Array]" !== Object.prototype.toString.call(scr.scripts)) return;
            for (var r = 0; r < scr.scripts.length; r++) {
                var c = document.createElement("script"), e = scr.scripts[r];
                c.src = e.src;
                c.async = false;
                document.body.appendChild(c);
            }
        }
    }();
</script>
</html>
```
Unfortunately I don't have sources of libs.min.js. I took it from some site I was playing with.

It's strange, that bug disappears, when scripts are loading through the tag, not through js, or if `chromedp.Query("a.toggle-nav", chromedp.ByQuery),` removed.

#### What did you expect to see?
xpath to `a[href='#mm-2']` should be `/html[1]/body[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]`.
You can check it, by open `template.html` in chrome and run 
`$x('/html[1]/body[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]')[0]` and `document.querySelector('a[href='#mm-2']')` in console.

#### What did you see instead?
Instead xpath is `/html[1]/body[1]/div[3]/div[1]/div[1]/ul[1]/li[1]/a[1]`.

**Comment by kenshaw** [comment]
Appreciate the work. I'll look at this in the morning. If I had to guess, the difference in xpath is because the DOM is still changing. There can definitely be sync issues with the DOM that's represented on Go, as not all of the events may have finished processing before the `FullXPath()` call returns.

**Comment by ZzEeKkAa** [comment]
@kenshaw thank you!
I guess so, but it is not true. `FullXPath()` doesn't change over time. Changing Tasks to
```go
chromedp.Navigate("file://" + absPath),
chromedp.Query("a.toggle-nav", chromedp.ByQuery),
chromedp.QueryAfter("a[href='#mm-2']", func(ctx context.Context, nodes ...*cdp.Node) error {
	fullPath := nodes[0].FullXPath()
	fmt.Println("[[FullXPath]]", fullPath)
	if fullPath != "/html[1]/body[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]" {
		//return errors.New("wrong path")
	}
	return nil
}, chromedp.ByQuery),
chromedp.Sleep(time.Second * 10),
chromedp.QueryAfter("a[href='#mm-2']", func(ctx context.Context, nodes ...*cdp.Node) error {
	fullPath := nodes[0].FullXPath()
	fmt.Println("[[FullXPath]]", fullPath)
	if fullPath != "/html[1]/body[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]" {
		return errors.New("wrong path")
	}
	return nil
}, chromedp.ByQuery),
```
will show you, that xpath, didn't change even after 10s

**Comment by ZzEeKkAa** [comment]
Here are some updates and possible solution. Problem is more likely with timing and old cache of DOM tree, `chromedp.Sleep(time.Second)` after `Navigate` solves the issue. It would be nice to have function to reload dom tree. There should be easier way, but following issue still is not resolved: https://github.com/ChromeDevTools/devtools-protocol/issues/20.
So `DOM.getDocument, DOM.requestChildNodes` is still only one solution, I guess =(
Alternatively, It is possible to create event listeners for DOM Mutations and update local copy of DOM in real time. https://developers.google.com/web/updates/2012/02/Detect-DOM-changes-with-Mutation-Observers

**Comment by ZzEeKkAa** [comment]
It would be really nice to have feature to get js object not through xpath, but through something more stable. Unfortunately I could not find anything. The only think I think can be 100% stable is to put background Javascript on pause, build valid xpath, run snippet, resume background javascript.

**Comment by kenshaw** [comment]
In the original versions of `chromedp`, I can assure you `FullXPath` worked when dom nodes changed. Either this is due to the recent refactor, where we more or less rewrote all of the internals, and (accidentally) stripped out most frame invalidation and the event handlers for the node updates. Also a possibility (however much more unlikely) is that Chrome has changed how dom modifications are sent to attached clients.

**Comment by kenshaw** [comment]
@ZzEeKkAa so -- the expected behavior of Chrome (or at least it used to be -- assuming it still is) was that after the client sent a request for specific child nodes, then all the nodeIds that had been returned would be tracked by Chrome and any subsequent updates on those nodes would be sent as async events to the attached client (ie, the various `cdproto/page.Event*` handling on `chromedp.Target`).

I'm going through the target handling code now, and I need to cross reference it with the actual nodes sent on the wire. Apologies on this.

**Comment by kenshaw** [comment]
I'm going through this now. The events (I believe) are being sent to `chromedp`, which means there could be a bug in the dom walking for inserting/removing nodes.

**Comment by kenshaw** [comment]
@ZzEeKkAa I believe I might have found the issue: not respecting the sibling ID on a add node event.

**Comment by kenshaw** [comment]
There's a very good chance that this is a 1-line, completely incorrect logic issue from the _original_ implementation 2 years ago, and has always been present. The issue (possibly) isn't with `FullXPath`, as I've verified that the way the dom `insertNode` node operation was treating previous IDs.

This simple change:
```patch
diff --git a/util.go b/util.go
index 066fa15..05add01 100644
--- a/util.go
+++ b/util.go
@@ -247,7 +247,7 @@ func insertNode(n []*cdp.Node, prevID cdp.NodeID, c *cdp.Node) []*cdp.Node {
        }
 
        if !found {
-               return append(n, c)
+               return append([]*cdp.Node{c}, n...)
        }
 
        i++
```

Is the change in behavior. I need to closely review and examine this change, before we merge it into master, as I really do not know what the correct behavior should be.

An explanation of the issue, if the above change is, indeed the correct change:

In the initial implementation, when adding a child node on a insert (add) event, I had thought that when the previous node ID was 0, that it meant to insert it at the _end_ of the list. If instead this meant insert it at the _head_ of the list, then this logic has been completely flopped for the entirety of the existence of this project. It has been hard to track down, because the previous issues reporting problems with `FullXPath` this did not supply specific HTML + JavaScript that would have allowed me to track this down readily. Additionally, the tree building logic is partially correct, and would not cause issues when there are no other siblings, and was meant to be inserted at the beginning.

Apologies to all. I will be digging through many different projects to determine the correct behavior, because unfortunately the DevTools Protocol documentation doesn't seem to cover this in depth. In the interim, if the above change works for you, I'd suggest temporarily using a GitHub fork with that applied in your project(s).

**Comment by kenshaw** [comment]
@ZzEeKkAa can you apply this change in your code and let me know if that fixes the specific issue you were using with the original code you were attempting this with?

**Comment by kenshaw** [comment]
I'm fairly certain this change is necessary, however due to the potential backwards compatibility issues, we are likely to defer adding this until v0.4.0

**Comment by ZzEeKkAa** [comment]
@kenshaw thank you! It looks like the problem is solved. Thanks to you, I was able to create clear test, to show the root of the problem:

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"path/filepath"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/chromedp"
)

const jsSnippet = `(function() {
	var body = document.querySelector("body");
	var div = document.createElement("div");
	div.id="div2";
	div.innerText = "div2";
	%s;
	return {};
})()
`

func insert(f string) chromedp.Action {
	var res interface{}
	return chromedp.Evaluate(fmt.Sprintf(jsSnippet, f), &res)
}

func assertXPath(sel, needle string) chromedp.Action {
	return chromedp.QueryAfter(sel, func(ctx context.Context, nodes ...*cdp.Node) error {
		if len(nodes) < 1 {
			return errors.New("nodes not found")
		}
		fullPath := nodes[0].FullXPath()
		if fullPath != needle {
			return fmt.Errorf("fullPath mismatch: got %s, want %s", fullPath, needle)
		}
		return nil
	}, chromedp.ByQuery)
}

func main() {
	absPath, err := filepath.Abs("template.html")
	if err != nil {
		panic(err)
	}

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	if err := chromedp.Run(ctx, chromedp.Tasks{
		// Test 1
		chromedp.Navigate("file://" + absPath),
		assertXPath("#div1", "/html[1]/body[1]/div[1]"), // this line is required to build DOM before js.
		insert("body.appendChild(div)"),
		assertXPath("#div1", "/html[1]/body[1]/div[1]"),
		assertXPath("#div2", "/html[1]/body[1]/div[2]"),
		// Test 2
		chromedp.Navigate("file://" + absPath),
		assertXPath("#div1", "/html[1]/body[1]/div[1]"), // this line is required to build DOM before js.
		insert("body.insertBefore(div,body.childNodes[0])"),
		assertXPath("#div1", "/html[1]/body[1]/div[2]"), // this check will fail, without fix.
		assertXPath("#div2", "/html[1]/body[1]/div[1]"),
	}); err != nil {
		log.Fatal(err)
	}
}
```

```html
<!DOCTYPE html>
<html>
<body>
    <div id="div1">div1</div>
</body>
</html>
```

you can also check it on my git repo. It is also updated.
