### ISSUE TITLE
macbook: chrome quit, when close the lid of macbook

### ISSUE THREAD

**Issue by ii0** [chromedp/chromedp#449]
#### What versions are you running?

<pre>
macos version:
10.14.5

chromedp:
"revision": "f6a51f2349aafd65be469c82cadc7b9e287de363"

$ google-chrome --version
76.0.3809.87

$ go version
go version go1.12 darwin/amd64
</pre>

#### What did you do? Include clear steps.
when close the lid of macbook, and reopen the lid, chrome quit

#### What did you expect to see?
when close the lid of macbook, and reopen the lid, keep chrome alive, don't quit

**Comment by mvdan** [comment]
What happens when you close your macbook's lid? It simply suspends to memory?

I assume a regular Chrome that you run manually doesn't close like this?

What exactly does your chromedp program do when the lid is closed?

Finally, please provide a small program to reproduce this. Otherwise we have to take guesses to try to reproduce the problem.

**Comment by mvdan** [comment]
Friendly ping @ii0; this isn't enough information for us to look into the issue.

**Comment by mvdan** [comment]
Sorry, but I can't debug or fix a bug I can't even reproduce. Closing for now.
