### ISSUE TITLE
Possible to toggle headless mode?

### ISSUE THREAD

**Issue by JohnStarich** [chromedp/chromedp#518]
Is it possible to toggle headless mode on and off while running a browser instance? Or, perhaps, is it possible to transfer state to a new, non-headless instance?

My use case involves auto-signing into a website, but sometimes the landing page is unexpected and requires human intervention. Ideally, this could be solved with a "switch to foreground/non-headless mode" once that bad page is detected.

#### What versions are you running?

Not sure if this is required for a question, but here goes! :smile:

```bash
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.1
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 78.0.3904.108
$ go version
go version go1.12.12 darwin/amd64
```

(Note: I am also targeting Windows and Debian)

#### What did you do? Include clear steps.

I searched through chromedp's and puppeteer's documentation and issues but didn't find much guidance for this. Perhaps the closest issue was https://github.com/chromedp/chromedp/issues/171 but that's more about using an existing foreground chrome instance.

#### What did you expect to see?

I think something like this would be perfect (though likely hard, if not impossible to achieve):
```go
if unexpectedLandingPage {
	chromedp.Run(ctx,
		chromedp.SetHeadless(false),
	)
}
```

#### What did you see instead?

It appears chromedp and puppeteer only send either `--headless=true` or `false`. Do you all have any advice for possible solutions here?

**Comment by mvdan** [comment]
You're really asking for a Chrome feature here; we can only expose the features the browser has.

If Puppeteer doesn't support something like this, it's highly unlikely we can, for the reason above.

I only see two alternatives:

* Using a headless browser, and taking screenshots of the page when you encounter an error
* Using a non-headless browser with a virtual output (e.g. `Xvfb`), and showing the virtual output to the user when needed

I'm going to close this issue, because I don't think there's anything we can do here.

**Comment by JohnStarich** [comment]
Ok, thanks for your advice. Much appreciated 🙂
