### ISSUE TITLE
potential heap memory leak when cancelling a browser context

### ISSUE THREAD

**Issue by mesuutt** [chromedp/chromedp#552]
#### What versions are you running?
```sh
github.com/chromedp/chromedp v0.4.2
Chromium 79.0.3945.117 Arch Linux
go version go1.13.5 linux/amd64
```

I am running `chromedp.Run` in endless loop. 
chromedp not flushing heap after context cancelled.

I copied [click](https://github.com/chromedp/examples/blob/master/click/main.go) example  and runned it in for loop. When I look at pprof, heap allocation increasing on every `chromedp.Run`

You can test at [http://localhost:8080/debug/pprof/](http://localhost:8080/debug/pprof/) after run the app.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/gin-contrib/pprof"
	"github.com/gin-gonic/gin"
)

func main() {
	router := gin.Default()
	go func() {
		for {
			click()
		}
	}()
	pprof.Register(router)
	router.Run(":8080")

}

func click() {
	// create chrome instance
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	// create a timeout
	ctx, cancel = context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	// navigate to a page, wait for an element, click
	var example string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://golang.org/pkg/time/`),
		// wait for footer element is visible (ie, page is loaded)
		chromedp.WaitVisible(`body > footer`),
		// find and click "Expand All" link
		chromedp.Click(`#pkg-examples > div`, chromedp.NodeVisible),
		// retrieve the value of the textarea
		chromedp.Value(`#example_After .play .input textarea`, &example),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)
}


```

**Comment by Ajod** [comment]
Hi,

Unless that's exactly what you wanted to do, here you are opening a new chrome browser, navigating, clicking, closing the browser and opening a new one right away.
With browsers there's bound to be a little bit of lingering overhead especially if you open and close dozens of browsers per minute.
 I assume doing that isn't healthy no matter the browser but i'm curious about this:
Since you open/close chrome browsers in a loop, could this be stacking google chrome "software reporter tool" processes ? It does this to me if I open/close chrome manually, and they take a long time to go away (~10min) while being quite heavy for a background process.

**Comment by mesuutt** [comment]
I think this memory leak not related with the browser because browser is an external executable. pprof cannot count browser's heap allocations. 

The code is for demonstration purpose only.
We are crawling some websites everyday with chromedp and closing the browser instances after done. But we dont close the go app so heap allocations increasing everyday and not flushing after some minutes or hours.

**Comment by mvdan** [comment]
Thanks for filing this bug. It's entirely possible that there is a goroutine leak somewhere, in one of the edge cases; it's an easy mistake to make.

I'll note that your code above isn't entirely correct, though. Context cancellation simply signals for goroutines to stop, it doesn't wait for them to actually stop. It might take microseconds or even milliseconds for them to actually reach a `select` again and exit.

In the long term, if you actually want to block until all resources are cleaned up (this includes goroutines exiting, temporary directories being removed, child processes finishing, etc), you should use https://godoc.org/github.com/chromedp/chromedp#Cancel, which is meant for that purpose. It also returns an error, for example if the temporary directory could not be deleted and you are "leaking" files on disk.

If someone wants to investigate here or work on a patch, that would be welcome. Otherwise I'll have a look at some point.

**Comment by mesuutt** [comment]
I tried `chromedp.Close()` instead cancel with above example, The `Cancel` func not return any error  and memory allocations still increasing.

**Comment by mvdan** [comment]
Yes, I realise that there might be a leak. I was just noting that there is no way that your code above could ever reliably clean up after itself.

**Comment by mvdan** [comment]
Well, I've investigated a bit, but found nothing. I used a local godoc server, so that I could start and stop hundreds of browsers faster and without consuming too much network. Below is the code I ran against master:

```
// +build ignore

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"runtime"
	"runtime/pprof"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	for i := 0; i < 100; i++ {
		click()
		var m runtime.MemStats
		runtime.ReadMemStats(&m)
		fmt.Printf("Alloc: % 10d\n", m.Alloc)
	}

	f, err := os.Create("mem.out")
	if err != nil {
		log.Fatal("could not create memory profile: ", err)
	}
	defer f.Close()
	runtime.GC()
	if err := pprof.WriteHeapProfile(f); err != nil {
		log.Fatal("could not write memory profile: ", err)
	}
}

func click() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate(`http://localhost:6060/pkg/time/`),
		chromedp.WaitVisible(`#footer`),
		chromedp.Click(`#pkg-examples > div`, chromedp.NodeVisible),
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := chromedp.Cancel(ctx); err != nil {
		log.Fatal(err)
	}
}
```

With the resulting heap profile, I could not find anything out of the ordinary with `go tool pprof -inuse_space mem.out`. Just a few megabytes of data are used.

The `MemStats.Alloc` number does kind of go up over time, but it doesn't really go beyond one gigabyte for me. Given that the heap profile doesn't show a leak, I think that's just the GC letting the program hold onto a bunch of not-really-used memory.

**Comment by mesuutt** [comment]
The app working 6 days and  app's pprof output is as shown as below:
![1579690546](https://user-images.githubusercontent.com/823338/72888690-155e3f00-3d1f-11ea-8e3b-bccb47ac4cac.png)

The `allocs` and `heap` increasing continiously.
Do pprof heap and alloc count means total allocations(using + flushed) or only using?

Allocs from newrelic:
![1579690817](https://user-images.githubusercontent.com/823338/72888932-a2a19380-3d1f-11ea-9200-6d98d036fbbd.png)

**Comment by mpx** [comment]
I have a process that periodically calls `chromedp.Run` to scrape some data. The context is always cancelled which should release associated resources.

However, heap usage climbs steadily. My latest instance instance has 1GB allocated under:
`chromedp.Run` -> `chromedp.(*ExecAllocator).Allocate` -> `chromedp.NewBrowser` -> `chromedp.DialContext`

There is an associated goroutine leak at:
`github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func4+0x27`
This goroutine is waiting for `<-browser.LostConnection`, and is pinning each browser allocation. My latest instance has leaked 1080+ goroutines.

The `LostConnection` channel is only closed from `chromedp.(*Browser).run` after the websocket `Read` fails. However, if the Read succeeds but the context is cancelled, it will return without closing `LostConnection`. This leaks the cleanup goroutine and associated `Browser` memory.

The above pull request ensures the cleanup goroutine runs and prevents the memory being pinned.

**Comment by mpx** [comment]
I have been running the above fix for ~2 weeks now. Looks good:

![goroutine-leak-fixed](https://user-images.githubusercontent.com/1345076/103496446-61ec4d00-4e92-11eb-806c-8e72553ac9ee.png)

**Comment by kenshaw** [comment]
@mpx thanks, it's appreciated. Apologies for not being on top of this; but 2020 issues have kept me busy with other code projects. `chromedp` is slated for a overhaul though (as is always planned ... hah!). Cheers, and again, thanks!

**Comment by mpx** [comment]
@kenshaw, all good, everyone is busy (especially this time of year) and I'm not paying for support :). Chromedp has saved me a lot of effort. Thanks for the quick v0.5.5 tag as well.
