### ISSUE TITLE
broken https://github.com/chromedp/examples/blob/master/headers/

### ISSUE THREAD

**Issue by Dexus** [chromedp/chromedp#560]
#### What versions are you running?

<pre>
$ github.com/chromedp/cdproto v0.0.0-20200116234248-4da64dd111ac
$ github.com/chromedp/chromedp v0.5.3
$ google-chrome --version latest
$ go version latest
</pre>

#### What did you expect to see?
https://github.com/chromedp/examples/blob/master/headers/ working

#### What did you see instead?

https://github.com/chromedp/examples/blob/master/headers/ broken

**Comment by mvdan** [comment]
Please follow the template. What did you do?

**Comment by pmurley** [comment]
I'll provide a little more info here, because I am seeing stuff breaking as well. Looks like JSON messages failing to parse after a recent update to either chromedp or cdproto.

### What did you do? Include clear steps.

I ran previously-working chromedp code driving Chrome.

### What did you expect to see?

I expected to see the code working as before.

### What did you see instead?

The browser still opens, but there are immediately errors that appear to be related to parsing DevTools protocol messages from the browser:
```
2020/01/17 11:00:59 ERROR: could not unmarshal event: parse error: expected string near offset 193 of 'headers'
2020/01/17 11:00:59 ERROR: could not unmarshal event: parse error: expected string near offset 100 of 'headers'
```
All of the other browser-driving code fails to run after these errors.

**Comment by Dexus** [comment]
clone it and execute it...

the example is broken because now `type Headers easyjson.RawMessage` has been replaced by `type Headers map[string]interface{}`.

**Comment by pmurley** [comment]
I would imagine this is related to chromedp/cdproto@4da64dd. The commit message indicates something that seems related, but I don't quite have it nailed down yet.
```
Updating cdproto dependency which introduced some slight,
backwards-incompatible name changes of types.
```

**Comment by Dexus** [comment]
It looks to me as if the headers are not passed correctly and/or are not processed correctly. Because the error "Invalid parameters (-32602)" is issued when I execute the following code:

```go
        toGenHeaders := map[string]interface{}{
		"Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
	}
	var err error
	_ = err
	headersBrowser, err = json.Marshal(toGenHeaders)
	// ensure that the browser process is started
	if err := chromedp.Run(c,
		network.Enable(),
		network.SetExtraHTTPHeaders(network.Headers(headersBrowser)),
		chromedp.Navigate("https://m.facebook.com/"),
		//chromedp.Nodes(`document`, &nodes, chromedp.ByJSPath),
		chromedp.WaitVisible(emailField),
		chromedp.WaitVisible(passwordField),
		chromedp.SendKeys(emailField, viper.GetString("login.email")),
		chromedp.SendKeys(passwordField, viper.GetString("login.passwd")),
		chromedp.WaitReady(`//*[@id="signup-button"]`),
		chromedp.Click(`//*[@name="login"]`),
		chromedp.Sleep(2*time.Second),
	); err != nil {
		log.Println(page)
		log.Println(err)
		return
		//panic(err)
	}
```

**Comment by Dexus** [comment]
It looks to me as if the headers are not passed correctly and/or are not processed correctly. Because the error "Invalid parameters (-32602)" is issued when I execute the following code:

```go
        toGenHeaders := map[string]interface{}{
		"Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
	}
	var err error
	_ = err
	headersBrowser, err = json.Marshal(toGenHeaders)
	// ensure that the browser process is started
	if err := chromedp.Run(c,
		network.Enable(),
		network.SetExtraHTTPHeaders(network.Headers(headersBrowser)),
		chromedp.Navigate("https://local.page/"),
		//chromedp.Nodes(`document`, &nodes, chromedp.ByJSPath),
		chromedp.WaitVisible(emailField),
		chromedp.WaitVisible(passwordField),
		chromedp.SendKeys(emailField, viper.GetString("login.email")),
		chromedp.SendKeys(passwordField, viper.GetString("login.passwd")),
		chromedp.WaitReady(`//*[@id="signup-button"]`),
		chromedp.Click(`//*[@name="login"]`),
		chromedp.Sleep(2*time.Second),
	); err != nil {
		log.Println(page)
		log.Println(err)
		return
		//panic(err)
	}
```

**Comment by Dexus** [comment]
As per https://github.com/chromedp/cdproto-gen/blob/master/fixup/fixup.go#L216-L220

The `Headers` type should be fixed to `map[string]interface{}` but it is not. Think the https://github.com/chromedp/cdproto-gen is broken...

**Comment by mvdan** [comment]
First things first - you should really be using Go modules, which is on by default with Go 1.13. This is precisely why I wanted more information, not just `go version latest` and so on.

If I run the example with modules, it uses chromedp `v0.4.2` and an older `cdproto`, and it works.

Yes, the example seems to be incompatible with the latest versions due to a change in cdproto, I'm looking at that now. But it's not broken, because we haven't updated go.mod with those versions.

**Comment by mvdan** [comment]
Fixed in https://github.com/chromedp/cdproto-gen/commit/5017836d2c839513555503c7fbbd884daafdf467 and https://github.com/chromedp/cdproto/commit/82dd5aea4c2632bc151af34551b999438b5d08db.

**Comment by Dexus** [comment]
Ok, sorry you are right. I forgot to say that I update the go.mod with `go get -u` but thats why i post the versions of the both. ;)
