### ISSUE TITLE
clipboardReadWrite browser permission is obsolete

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#575]
Looks like `clipboardReadWrite` (https://github.com/chromedp/cdproto/blob/5a93cbf1c808f662bbec5ac855626008ca933acc/browser/types.go#L100) is now two separate permissions: `clipboardRead` and `clipboardWrite`.

#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.4-0.20200201212839-2c48f1180a35
$ google-chrome --version
Google Chrome 79.0.3945.130
$ go version
go version go1.13.4 linux/amd64
</pre>

#### What did you do? Include clear steps.

``` go
package main

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/chromedp/cdproto/browser"
	"github.com/chromedp/chromedp"
)

func main() {
	go func() {
		http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprint(w, `<!DOCTYPE html><html><body></body></html>`)
		})
		http.ListenAndServe(":3000", nil)
	}()

	time.Sleep(time.Second)

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:3000"),
		browser.GrantPermissions("http://localhost:3000", []browser.PermissionType{
			browser.PermissionTypeClipboardReadWrite,
		}),
	); err != nil {
		panic(err)
	}
}
```

#### What did you expect to see?

No errors.

#### What did you see instead?

`panic: Unknown permission type: clipboardReadWrite (-32602)`

**Comment by opennota** [comment]
Well, I can just use string literals:

```
browser.GrantPermissions("http://localhost:3000", []browser.PermissionType{
  "clipboardRead", "clipboardWrite",
}),
```

**Comment by kenshaw** [comment]
@opennota -- this isn't really related to `chromedp` (ie, this repository). The protocol layer used by `chromedp` is auto-generated by the `cdproto-gen` tool. Issues pertaining to the protocol layer should be posted to the `cdproto` repository.

But, no problem: anyway, I manually verified in the `browser_protocol.pdl` file that these are the correct definitions, and that the auto-generated `cdproto` package is "correct".

Let me explain:

Primarily out of necessity, and, in order to try and keep pace with the Chromium source tree, `cdproto-gen` generates the protocol layer (ie, `cdproto`) based on the the master branch of Chromium. Chromium is probably the fastest "moving" source tree in the world, and this can be a bit annoying to deal with at times, as it causes breakage in downstream projects like yours and in `chromedp`.

Per the current [`browser_protocol.pdl`](https://chromium.googlesource.com/chromium/src/+/82.0.4054.2/third_party/blink/public/devtools_protocol/browser_protocol.pdl?format=TEXT), these are the correct/changed definitions, and this seemed to change sometime between Chromium 80.0.3984.2 and 81.0.4029.3. 

For what it's worth, the API you're using is tagged as "experimental" in the definitions and, as such, is prone to change/breakage by the Chromium team without advance warning. I'd suggest staying away from using Chrome's "experimental" APIs unless you also pin the specific version of `chromedp` and `cdproto` you're using with your version of Chrome/ium.
