### ISSUE TITLE
Method and Return Type

### ISSUE THREAD

**Issue by AngangGuo** [chromedp/chromedp#583]
From the [AcceptAlert example](https://pkg.go.dev/github.com/chromedp/chromedp@v0.5.3?tab=doc#example-ListenTarget-AcceptAlert) in chromedp document, there's a line like this:
```
if ev, ok := ev.(*page.EventJavascriptDialogOpening); ok {
```

I can find the type definition for `EventJavascriptDialogOpening` fron [here](https://pkg.go.dev/github.com/chromedp/cdproto/page?tab=doc#EventJavascriptDialogOpening) 

Where can I find the document for the method `ev.(*page.EventJavascriptDialogOpening)` and definition of their returned values.

Thanks.

**Comment by kenshaw** [comment]
@AngangGuo -- I'm going to assume you're fairly new to Go. If you happen to be experienced with Go, please don't be upset, as this is for the benefit of others who may find this.

For reference, this is the `ListenTarget` call from within `ExampleListenTarget_acceptAlert()`:

```go
chromedp.ListenTarget(ctx, func(ev interface{}) {    
    if ev, ok := ev.(*page.EventJavascriptDialogOpening); ok { 
        fmt.Println("closing alert:", ev.Message)
        /* ... */
    }
}
```

Specifically, from the [example](https://godoc.org/github.com/chromedp/chromedp#example-ListenTarget--AcceptAlert), the `chromedp.ListenTarget` call is adding a _callback_ func (with signature `func(interface{}) {}`) that will be called for every received event on that target. A "target" is a "Chrome Page Target", which is comparable to a browser tab.

Since `chromedp` is type-safe, and we only pass fully structured event types, the callback (ie, `func(interface{}) {}`) needs to do a type assertion from `interface{}` to whatever event type is being listened for. 

Specifically, that is done by the code here:

```go
if ev, ok := ev.(*page.EventJavascriptDialogOpening); ok { /* ... */ }
```

In this case, `ev` is being converted to a pointer to the `chromedp/cdproto/page.EventJavascriptDialogOpening` type. This type is automatically generated from Chrome's Protocol Definitions (PDLs), and the documentation (which was linked in the documentation link you included in your comment) clearly indicates that this is taken from [here](https://chromedevtools.github.io/devtools-protocol/tot/Page#event-javascriptDialogOpening). 

_*An aside:* the generated `cdproto` types are directly equivalent (ie, have the same field names) as the what's seen in Chrome DevTools Protocol Viewer. The case of the names have been changed (slightly) in order to conform to requirements of the Go language. Additionally, event types are prefixed with `Event` in order to avoid some name conflicts in the packages, and to distinguish/group them together._

Getting back to this:

```go
if ev, ok := ev.(*page.EventJavascriptDialogOpening); ok { /* ... */ }
```

What's happening here is that two _new_ variables (`ev` and `ok`) are being declared, and the result of the type assertion is assigned to them. The choice of `ev` here was not a good one, as it clashes with the callback's `ev` parameter and is further complicated because its within the scope of the `if` statement. This can be a bit perplexing to those new to Go -- apologies, and a mea culpa.

Anyway, assuming the type assertion succeeded (meaning `ok == true`), then the `if` statement proceeds. If you'd like to read more about Go's type conversions, please [review the documentation here](https://tour.golang.org/methods/15). 

What's then executed is the _type asserted_ `ev`'s `Message` field being logged:

```go
fmt.Println("closing alert:", ev.Message)
```

That's the Chrome DevTools Protocol `Page.javascriptDialogOpening.message` field, and, as mentioned above, the names have been changed to reflect rules of the Go programming language. That field's fully qualified name is (essentially): `chromedp/cdproto/page/EventJavascriptDialogOpening.Message`.

I hope that can shed some light on the issue.

**Comment by AngangGuo** [comment]
@kenshaw I got it. 
Thank you very much for this great project and for this detailed explanation.
