### ISSUE TITLE
Help, how does Chromedp use other browsers (Edge, Safari, Android, etc)

### ISSUE THREAD

**Issue by RGDZ-GZU** [chromedp/chromedp#606]
#### What versions are you running?
latest version.

#### problem：
Recently I used Chromedp for some experiments, it is very efficient and interesting, but because the experiments I conducted also need to use other browsers for automated testing, I found relevant information through the search engine and found that chromedp supports other browsers, For example (Chrome, Edge, Safari, Android, etc), I have been searching for a long time in issues, documents, and examples, but I have not found relevant sample code. Can you please provide me with how to use chromedp To drive other browser examples, or can you tell me which related API should I use, I would appreciate it. Thanks

**Comment by karel-3d** [comment]
Chromedp is tied to Chrome very explicitly.

**Comment by kenshaw** [comment]
@RGDZ-GZU previously, there were adapters for using Chrome DevTools Protocol with with Edge. Since Edge is now Chrome based, they are no longer necessary. Additionally, there is also a CDP adapter available for Firefox and for Android. It's no longer the goal of this project to support anything other than Chrome, however.

**Comment by RGDZ-GZU** [comment]
Ok, I am trying to experiment with the new version of Edge and Chrome. Thank you very much for your reply.
