### ISSUE TITLE
# github.com/chromedp/chromedp /go/src/github.com/chromedp/chromedp/chromedp.go:157:15: assignment mismatch: 2 variables but action.Do returns 1 values

### ISSUE THREAD

**Issue by TaroballzChen** [chromedp/chromedp#733]
#### What versions are you running?

<pre>
$ google-chrome --version
Google Chrome 87.0.4280.88
$ go version
go version go1.15.5 darwin/amd64
</pre>

#### What did you do? Include clear steps.
```go
package main 
  
import ( 
        _ "github.com/chromedp/chromedp" 
) 
 
 
func main(){ 
 
}

```

#### What did you expect to see?
no error must be handle

#### What did you see instead?
```cmd
# github.com/chromedp/chromedp
/go/src/github.com/chromedp/chromedp/chromedp.go:157:15: assignment mismatch: 2 variables but action.Do returns 1 values
```

**Comment by kenshaw** [comment]
You need to update to the latest version of `chromedp` and `cdproto`. I updated the generated definitions for `cdproto` yesterday (and subsequently tagged `v0.6.0` due to this issue). Unfortunately, chromium doesn't follow semver practices, otherwise it'd be somewhat easier to tag these issues. Update to the latest `chromedp` and `cdproto` and you should be fine.
