### ISSUE TITLE
Is there an easy way to set cookie?

### ISSUE THREAD

**Issue by hsluoyz** [chromedp/chromedp#754]
I saw the example here: https://github.com/chromedp/examples/blob/master/cookie/main.go , but it looks a little too complicated. For example, I don't know what a cookieServer is used for.

Moreover, the `setcookies()` function seems to do something like "read the returned values". In my case, I already know what cookie I need to set as follows, including cookie name, value, domain and all other properties (by logging in the site manually). I just need to set these static cookie info into ChromeDP.

![image](https://user-images.githubusercontent.com/3787410/108666292-bd8d9b00-7511-11eb-9474-33ace1e6f782.png)

I want to have a simple API like:

```go
err := chromedp.Run(ctx,
		chromedp.SetCookie(cookie), // key1 = value1
		chromedp.Navigate(url),

		chromedp.Sleep(1*time.Second),
		chromedp.SendKeys(`//*[@id="username"]`, username),
		chromedp.SendKeys(`//*[@id="loginform"]/div[3]/input`, password),
		chromedp.Click(`//*[@id="btn-login"]`),
	)
	if err != nil {
		panic(err)
	}
```

Is it possible?

**Comment by ZekeLu** [comment]
The example illustrates many things,  that's why it looks "complicated":

1. It sets browser cookies ([L70-L85](https://github.com/chromedp/examples/blob/3904eac11bc856019572718bf4d5edb081095e42/cookie/main.go#L70-L85));
2. It reads browser cookies ([L90-L102](https://github.com/chromedp/examples/blob/3904eac11bc856019572718bf4d5edb081095e42/cookie/main.go#L90-L102)).
3. It event provides a simple web server to illustrate that the provided cookies are sent to the server ([ cookieServer](https://github.com/chromedp/examples/blob/3904eac11bc856019572718bf4d5edb081095e42/cookie/main.go#L45-L61));

The source code in Part 1 is what you need.

BTW, I think it's a bad idea to wait like this: `chromedp.Sleep(1*time.Second)`. Try to use one of the following actions:

* `chromedp.WaitReady`
* `chromedp.WaitVisible`
* `chromedp.WaitEnabled`
* and any other query actions

**Comment by hsluoyz** [comment]
Thanks!

**Comment by hzmnet** [comment]
but the  document.cookie is null

**Comment by ZekeLu** [comment]
@hzmnet Please provide a minimal demo to show what's wrong.

**Comment by hzmnet** [comment]
@ZekeLu please check to run the code document.cookie
