### ISSUE TITLE
chromedp.ListenTarget has chrome ext chrome.webRequest api?

### ISSUE THREAD

**Issue by baerwang** [chromedp/chromedp#846]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
Google Chrome 90.0.4430.93
$ go version
go version go1.16.4 windows/amd64
```

```js
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    chrome.webRequest.onBeforeRequest.addListener(() => {
            return {redirectUrl: 'javascript:void(0);'};
        },
        {urls: ["<all_urls>"]},
        ["blocking"]
    );
})
```

**Comment by baerwang** [comment]
@ZekeLu

**Comment by baerwang** [comment]
@ZekeLu do you know? Please reply if you don’t know, thank you

**Comment by ZekeLu** [comment]
@baerwang To be clear: we use the issue tracker for bugs and feature requests, **we don't use the issue tracker for support.**

If you have read the doc and tried everything you can and you're still stuck, then you can ask the question here. Others with the same experience would be glad to help you. And those kind of questions will be helpful for others too.

If you ask a vague question without reading the doc and trying, that won't be helpful and it's very rarely that you will get an answer.

And please be respectful. Otherwise, I have to block you.

**Comment by baerwang** [comment]
@ZekeLu I said whether this chromedp.ListenTarget has the webRequest api of the chrome plug-in? Speaking not clearly enough?

**Comment by ZekeLu** [comment]
@baerwang You have asked several questions in this project, but none is clear. Can you please learn how to ask a question first?

Here are some references:

*  [The XY Problem](https://xyproblem.info/)
*  [Don't ask to ask, just ask](https://dontasktoask.com/)
*  [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
*  [How To Ask Questions The Smart Way](http://catb.org/~esr/faqs/smart-questions.html)

Thank you!
