### ISSUE TITLE
'DOM.scrollIntoViewIfNeeded' wasn't found

### ISSUE THREAD

**Issue by FournyP** [chromedp/chromedp#881]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
Chromium 75.0.3770.142
$ go version
go version go1.16.6 windows/amd64
```

#### What did you do? Include clear steps.

Hello everyone, I have a problem with chromedp

I try to access to a web page thanks test and I got the error : `'DOM.scrollIntoViewIfNeeded' wasn't found (-32601)`

My code : 
```
// Emulate a mobile
err := chromedp.Emulate(device.IPhoneX).Do(c)
if err != nil {
   return err
}

// Go to register endpoint
err = chromedp.Navigate(REGISTER_ENDPOINT).Do(c)
if err != nil {
   return err
}

// Wait the cookie modal
chromedp.WaitVisible(COOKIE_BTN_SELECTOR).Do(c)
if err != nil {
   return err
}

// Accept cookies
err = chromedp.Click(COOKIE_BTN_SELECTOR).Do(c)
if err != nil {
   return err
}
```

I have update the dependencies and after that, my code return me this error, it worked before that.
The error appear when I run the "accept cookies" phase

#### What did you expect to see?
No error, like before

#### What did you see instead?
An error 'DOM.scrollIntoViewIfNeeded' wasn't found

Thanks for your help

Have a good day

**Comment by FournyP** [comment]
I have try to use scrollIntoViewIfNeeded func in a page with my version of Chromium and that work

A example to show it work :
![Image](https://i.ibb.co/bbj572n/image.png)

**Comment by ZekeLu** [comment]
Please upgrade your chromium. `DOM.scrollIntoViewIfNeeded` is a CDP command. It is needed in `chromedp v0.7.4`. Sorry that when I used it, I did not check which version of chromium started to support it, and failed to mention it in the release notes.

**Comment by ZekeLu** [comment]
Just read https://github.com/chromedp/chromedp/issues/877#issuecomment-881875183. IIRC, `chromedp.Flag("enable-automation", false)` should work in a  recent version of chromium. Please have a try and let me know the result. Thank you!

**Comment by FournyP** [comment]
Hello @ZekeLu 

I have installed the version 91.0.* version of chromium

The `enable-automation` didn't work :
![Image](https://i.ibb.co/bRDGpGc/image.png)

Google use the window.navigator.webdriver value to identify when the browser is controlled

Here the documentation of this :
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver

That work in the 75.0.* version

Do you know why ?

Have a good day and thanks you for your quick reply

**Comment by ZekeLu** [comment]
@FournyP I have searched the commit history of chromium, and I have a bad news. `window.navigator.webdriver` is set to true if any of the following switches is contained in the command line since `79.0.3922.0`:

- `enable-automation`
- `headless`
- `remote-debugging-pipe`
- `remote-debugging-port` (or `remote-debugging-port=0` since `86.0.4199.0`)

And `DOM.scrollIntoViewIfNeeded` is added in `82.0.4056.0`. So there is not an easy way to workaround the issue.

Here are the references:

- Additional switches to set EnableAutomationControlled: https://github.com/chromium/chromium/commit/a6e3413f883eec39b987612737aa8250957a80e3
- Leave navigator.webdriver undefined when attaching remote debugger: https://github.com/chromium/chromium/commit/c0a619c06981df4f8d6b7c7bf4c9014613ecb668
- DevTools protocol: introduce DOM.scrollIntoViewIfNeeded: https://github.com/chromium/chromium/commit/9a0d32249c8289b22e6f80813dbf1478e1fb09bf

So after `86.0.4199.0`, we have to set the following flags to make `window.navigator.webdriver` be false:

```go
// Set enable-automation to false alone is not enough to make
// `window.navigator.webdriver` be false since 79.0.3922.0.
// Headless mode should be disabled too, which is not acceptable
// for automation in my opinion.
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	chromedp.Flag("enable-automation", false),
	chromedp.Flag("headless", false),
	// any port other than "0" will work since 86.0.4199.0
	chromedp.Flag("remote-debugging-port", "9222"),
)
```

A better workaround is suggested by @pmurley in https://github.com/chromedp/chromedp/issues/557#issuecomment-575727046.

**Comment by FournyP** [comment]
@ZekeLu 

No problem, thank you for your reply

Have a good day

**Comment by dactoankmapydev** [comment]
when I sign in to my google account at https://accounts.google.com
I use flags
opts := append(chromedp.DefaultExecAllocatorOptions[:],
chromedp.Flag("headless", false),
chromedp.Flag("enable-automation", false),
chromedp.Flag("remote-debugging-port", "9222"),
)

then you can log in, without being warned that the browser is not secure.
Currently, I want to put it on the server to run, but I can't use flag
chromedp.Flag("headless", true)

how do i get it running on the server without chrome?
help me @ZekeLu
