### ISSUE TITLE
Compatibility of go1.18

### ISSUE THREAD

**Issue by jw-star** [chromedp/chromedp#993]
![image](https://user-images.githubusercontent.com/48782751/149254128-94f2cfca-30b1-48a6-845e-965941299fe1.png)

**Comment by jw-star** [comment]
go1.18 version log.Printf needs parameters, but it is not necessary in 1.17, you can switch to version 1.18 and try @kenshaw

**Comment by ZekeLu** [comment]
The source code compiles with go1.18 (run `go build` directly).

The error is reported by the IDE, it's an IDE issue.

**More information about the error**:

In vscode is, the error is:

```
cannot use log.Printf (value of type func(format string, v ...invalid type)) as func(string, ...interface{}) value in argument to chromedp.WithDebugf
```

That's because `interface{}` is rewritten to `any` in go1.18. (see https://github.com/golang/go/issues/49884). But there is not compatibility issue. It's just that the IDE is not updated to support it yet.

**Comment by jw-star** [comment]
Thanks, I know why!

**Comment by jw-star** [comment]
updated my goland to latest and the prompt disappeared
