### ISSUE TITLE
how to inherit the incognito mode as a tab?

### ISSUE THREAD

**Issue by xxxxnnxxxx** [chromedp/chromedp#997]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
96.0.4664.45 64bit
$ go version
go version go1.17.3 windows/amd64
```

#### What did you do? Include clear steps.

```go
func simplebrowser_incogintio() {
	ctx := context.Background()
	options := []chromedp.ExecAllocatorOption{
		chromedp.Flag("headless", false),
		chromedp.Flag("incognito", true),
		chromedp.Flag("no-first-run", true),
	}

	//options = append(chromedp.DefaultExecAllocatorOptions[:], options...)

	c, cc := chromedp.NewExecAllocator(ctx, options...)
	defer cc()
	// create context
	ctx1, cancel := chromedp.NewContext(c)
	defer cancel()
	chromedp.Run(ctx1, chromedp.Navigate("https://www.baidu.com"))

	ctx2, cancel2 := chromedp.NewContext(ctx1)
	defer cancel2()

	chromedp.Run(ctx2, chromedp.Navigate("https://www.qq.com"))

	time.Sleep(10000000 * time.Second)
}

func main() {
	simplebrowser_incogintio()
}

```

#### What did you expect to see?
two tabs are the incognito mode

#### What did you see instead?
the first is incognito mode, but the second not
why not inherit the ExecAllocator from the first context , i look up the doc:

```go
// NewContext creates a chromedp context from the parent context. The parent
// context's Allocator is inherited, defaulting to an ExecAllocator with
// DefaultExecAllocatorOptions.
//
// If the parent context contains an allocated Browser, the child context
// inherits it, and its first Run creates a new tab on that browser. Otherwise,
// its first Run will allocate a new browser.
//
// Cancelling the returned context will close a tab or an entire browser,
// depending on the logic described above. To cancel a context while checking
// for errors, see Cancel.
//
// Note that NewContext doesn't allocate nor start a browser; that happens the
// first time Run is used on the context.
func NewContext(parent context.Context, opts ...ContextOption) (context.Context, context.CancelFunc)
```
what's wrong with my code? i dont know how to solve the problem

**Comment by ZekeLu** [comment]
Thanks for reporting the issue.

First, Puppeteer supports "incognito" browser context. See [class: BrowserContext](https://pptr.dev/#?product=Puppeteer&version=v7.1.0&show=api-class-browsercontext). It implement this feature with the following CDP messages:
- [Target.createBrowserContext](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext)
- [Target.createTarget](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createTarget): with the `browserContextId` returned in the previous step.

`chromedp` does not implement such a feature out of the box. If you want to copy this feature, you have to call `target.CreateBrowserContext()` and `target.CreateTarget()` yourself. See the demo below:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)

	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
	defer cancel()

	var browserContextID cdp.BrowserContextID
	if err := chromedp.Run(ctx,
		chromedp.ActionFunc(func(c context.Context) error {
			var err error
			pc := chromedp.FromContext(c)
			browserContextID, err = target.CreateBrowserContext().Do(cdp.WithExecutor(c, pc.Browser))
			return err
		}),
	); err != nil {
		log.Fatal(err)
	}

	targetID1, err := createTarget(ctx, browserContextID)
	if err != nil {
		log.Fatal(err)
	}
	tabCtx1, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(targetID1))
	defer cancel()
	if err := chromedp.Run(tabCtx1, chromedp.Navigate("https://www.baidu.com")); err != nil {
		log.Fatal(err)
	}

	targetID2, err := createTarget(ctx, browserContextID)
	if err != nil {
		log.Fatal(err)
	}
	tabCtx2, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(targetID2))
	defer cancel()
	if err := chromedp.Run(tabCtx2, chromedp.Navigate("https://www.qq.com")); err != nil {
		log.Fatal(err)
	}

	time.Sleep(2 * time.Second)
}

func createTarget(ctx context.Context, browserContextID cdp.BrowserContextID) (target.ID, error) {
	var targetID target.ID
	err := chromedp.Run(ctx,
		chromedp.ActionFunc(func(c context.Context) error {
			var err error
			targetID, err = target.CreateTarget("about:blank").WithBrowserContextID(browserContextID).Do(c)
			return err
		}),
	)
	return targetID, err
}
```

Second, you see that the "incognito" browser context is not created by the `--incognito` flag. I have tried to get the id of the browser context created by the `--incognito` flag, and then pass it to `target.CreateTarget()`, but it results in an error:

```
2022/02/05 17:24:50 -> {"id":18,"method":"Target.createTarget","params":{"url":"about:blank","browserContextId":"71CD29D00F315420BE962463D6A3D293"}}
2022/02/05 17:24:50 <- {"id":18,"error":{"code":-32000,"message":"Failed to find browser context with id 71CD29D00F315420BE962463D6A3D293"}}
```

So I don't think that there is a workaround to make the `--incognito` flag work as what you expect.

Since `chromedp` will use a temporary user directory by default, and it will remove the user data directory finally. So technically, it's "incognito". Is there a use case that the default behavior is not enough?

**Comment by xxxxnnxxxx** [comment]
thanks, yes, i create a user data directory for a browser ,not found that the default behavior is not enough. my program will create a browser with incognito mode for a link, need too large cpu and memory. i want to change it, create a brower and with a link has a tab.

**Comment by ZekeLu** [comment]
> `chromedp` does not implement such a feature out of the box. If you want to copy this feature, you have to call `target.CreateBrowserContext()` and `target.CreateTarget()` yourself.

PR #1269 introduces the support for BrowserContext.
